# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.bytes import Bytes  # noqa: F401,E501
from swagger_server.models.eps_bearer_id import EpsBearerId  # noqa: F401,E501
from swagger_server import util


class EpsBearerInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ebi=None, pgw_s8u_fteid=None, bearer_level_qo_s=None):  # noqa: E501
        """EpsBearerInfo - a model defined in Swagger

        :param ebi: The ebi of this EpsBearerInfo.  # noqa: E501
        :type ebi: EpsBearerId
        :param pgw_s8u_fteid: The pgw_s8u_fteid of this EpsBearerInfo.  # noqa: E501
        :type pgw_s8u_fteid: Bytes
        :param bearer_level_qo_s: The bearer_level_qo_s of this EpsBearerInfo.  # noqa: E501
        :type bearer_level_qo_s: Bytes
        """
        self.swagger_types = {
            'ebi': EpsBearerId,
            'pgw_s8u_fteid': Bytes,
            'bearer_level_qo_s': Bytes
        }

        self.attribute_map = {
            'ebi': 'ebi',
            'pgw_s8u_fteid': 'pgwS8uFteid',
            'bearer_level_qo_s': 'bearerLevelQoS'
        }
        self._ebi = ebi
        self._pgw_s8u_fteid = pgw_s8u_fteid
        self._bearer_level_qo_s = bearer_level_qo_s

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EpsBearerInfo of this EpsBearerInfo.  # noqa: E501
        :rtype: EpsBearerInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ebi(self):
        """Gets the ebi of this EpsBearerInfo.


        :return: The ebi of this EpsBearerInfo.
        :rtype: EpsBearerId
        """
        return self._ebi

    @ebi.setter
    def ebi(self, ebi):
        """Sets the ebi of this EpsBearerInfo.


        :param ebi: The ebi of this EpsBearerInfo.
        :type ebi: EpsBearerId
        """
        if ebi is None:
            raise ValueError("Invalid value for `ebi`, must not be `None`")  # noqa: E501

        self._ebi = ebi

    @property
    def pgw_s8u_fteid(self):
        """Gets the pgw_s8u_fteid of this EpsBearerInfo.


        :return: The pgw_s8u_fteid of this EpsBearerInfo.
        :rtype: Bytes
        """
        return self._pgw_s8u_fteid

    @pgw_s8u_fteid.setter
    def pgw_s8u_fteid(self, pgw_s8u_fteid):
        """Sets the pgw_s8u_fteid of this EpsBearerInfo.


        :param pgw_s8u_fteid: The pgw_s8u_fteid of this EpsBearerInfo.
        :type pgw_s8u_fteid: Bytes
        """
        if pgw_s8u_fteid is None:
            raise ValueError("Invalid value for `pgw_s8u_fteid`, must not be `None`")  # noqa: E501

        self._pgw_s8u_fteid = pgw_s8u_fteid

    @property
    def bearer_level_qo_s(self):
        """Gets the bearer_level_qo_s of this EpsBearerInfo.


        :return: The bearer_level_qo_s of this EpsBearerInfo.
        :rtype: Bytes
        """
        return self._bearer_level_qo_s

    @bearer_level_qo_s.setter
    def bearer_level_qo_s(self, bearer_level_qo_s):
        """Sets the bearer_level_qo_s of this EpsBearerInfo.


        :param bearer_level_qo_s: The bearer_level_qo_s of this EpsBearerInfo.
        :type bearer_level_qo_s: Bytes
        """
        if bearer_level_qo_s is None:
            raise ValueError("Invalid value for `bearer_level_qo_s`, must not be `None`")  # noqa: E501

        self._bearer_level_qo_s = bearer_level_qo_s
