# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.bytes import Bytes  # noqa: F401,E501
from swagger_server import util


class EpsPdnCnxInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pgw_s8c_fteid=None, pgw_node_name=None):  # noqa: E501
        """EpsPdnCnxInfo - a model defined in Swagger

        :param pgw_s8c_fteid: The pgw_s8c_fteid of this EpsPdnCnxInfo.  # noqa: E501
        :type pgw_s8c_fteid: Bytes
        :param pgw_node_name: The pgw_node_name of this EpsPdnCnxInfo.  # noqa: E501
        :type pgw_node_name: Bytes
        """
        self.swagger_types = {
            'pgw_s8c_fteid': Bytes,
            'pgw_node_name': Bytes
        }

        self.attribute_map = {
            'pgw_s8c_fteid': 'pgwS8cFteid',
            'pgw_node_name': 'pgwNodeName'
        }
        self._pgw_s8c_fteid = pgw_s8c_fteid
        self._pgw_node_name = pgw_node_name

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The EpsPdnCnxInfo of this EpsPdnCnxInfo.  # noqa: E501
        :rtype: EpsPdnCnxInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pgw_s8c_fteid(self):
        """Gets the pgw_s8c_fteid of this EpsPdnCnxInfo.


        :return: The pgw_s8c_fteid of this EpsPdnCnxInfo.
        :rtype: Bytes
        """
        return self._pgw_s8c_fteid

    @pgw_s8c_fteid.setter
    def pgw_s8c_fteid(self, pgw_s8c_fteid):
        """Sets the pgw_s8c_fteid of this EpsPdnCnxInfo.


        :param pgw_s8c_fteid: The pgw_s8c_fteid of this EpsPdnCnxInfo.
        :type pgw_s8c_fteid: Bytes
        """
        if pgw_s8c_fteid is None:
            raise ValueError("Invalid value for `pgw_s8c_fteid`, must not be `None`")  # noqa: E501

        self._pgw_s8c_fteid = pgw_s8c_fteid

    @property
    def pgw_node_name(self):
        """Gets the pgw_node_name of this EpsPdnCnxInfo.


        :return: The pgw_node_name of this EpsPdnCnxInfo.
        :rtype: Bytes
        """
        return self._pgw_node_name

    @pgw_node_name.setter
    def pgw_node_name(self, pgw_node_name):
        """Sets the pgw_node_name of this EpsPdnCnxInfo.


        :param pgw_node_name: The pgw_node_name of this EpsPdnCnxInfo.
        :type pgw_node_name: Bytes
        """

        self._pgw_node_name = pgw_node_name
