# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.bit_rate import BitRate  # noqa: F401,E501
from swagger_server.models.notification_control import NotificationControl  # noqa: F401,E501
from swagger_server.models.packet_loss_rate import PacketLossRate  # noqa: F401,E501
from swagger_server import util


class GbrQosFlowInformation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, max_fbr_dl=None, max_fbr_ul=None, gua_fbr_dl=None, gua_fbr_ul=None, notif_control=None, max_packet_loss_rate_dl=None, max_packet_loss_rate_ul=None):  # noqa: E501
        """GbrQosFlowInformation - a model defined in Swagger

        :param max_fbr_dl: The max_fbr_dl of this GbrQosFlowInformation.  # noqa: E501
        :type max_fbr_dl: BitRate
        :param max_fbr_ul: The max_fbr_ul of this GbrQosFlowInformation.  # noqa: E501
        :type max_fbr_ul: BitRate
        :param gua_fbr_dl: The gua_fbr_dl of this GbrQosFlowInformation.  # noqa: E501
        :type gua_fbr_dl: BitRate
        :param gua_fbr_ul: The gua_fbr_ul of this GbrQosFlowInformation.  # noqa: E501
        :type gua_fbr_ul: BitRate
        :param notif_control: The notif_control of this GbrQosFlowInformation.  # noqa: E501
        :type notif_control: NotificationControl
        :param max_packet_loss_rate_dl: The max_packet_loss_rate_dl of this GbrQosFlowInformation.  # noqa: E501
        :type max_packet_loss_rate_dl: PacketLossRate
        :param max_packet_loss_rate_ul: The max_packet_loss_rate_ul of this GbrQosFlowInformation.  # noqa: E501
        :type max_packet_loss_rate_ul: PacketLossRate
        """
        self.swagger_types = {
            'max_fbr_dl': BitRate,
            'max_fbr_ul': BitRate,
            'gua_fbr_dl': BitRate,
            'gua_fbr_ul': BitRate,
            'notif_control': NotificationControl,
            'max_packet_loss_rate_dl': PacketLossRate,
            'max_packet_loss_rate_ul': PacketLossRate
        }

        self.attribute_map = {
            'max_fbr_dl': 'maxFbrDl',
            'max_fbr_ul': 'maxFbrUl',
            'gua_fbr_dl': 'guaFbrDl',
            'gua_fbr_ul': 'guaFbrUl',
            'notif_control': 'notifControl',
            'max_packet_loss_rate_dl': 'maxPacketLossRateDl',
            'max_packet_loss_rate_ul': 'maxPacketLossRateUl'
        }
        self._max_fbr_dl = max_fbr_dl
        self._max_fbr_ul = max_fbr_ul
        self._gua_fbr_dl = gua_fbr_dl
        self._gua_fbr_ul = gua_fbr_ul
        self._notif_control = notif_control
        self._max_packet_loss_rate_dl = max_packet_loss_rate_dl
        self._max_packet_loss_rate_ul = max_packet_loss_rate_ul

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GbrQosFlowInformation of this GbrQosFlowInformation.  # noqa: E501
        :rtype: GbrQosFlowInformation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def max_fbr_dl(self):
        """Gets the max_fbr_dl of this GbrQosFlowInformation.


        :return: The max_fbr_dl of this GbrQosFlowInformation.
        :rtype: BitRate
        """
        return self._max_fbr_dl

    @max_fbr_dl.setter
    def max_fbr_dl(self, max_fbr_dl):
        """Sets the max_fbr_dl of this GbrQosFlowInformation.


        :param max_fbr_dl: The max_fbr_dl of this GbrQosFlowInformation.
        :type max_fbr_dl: BitRate
        """
        if max_fbr_dl is None:
            raise ValueError("Invalid value for `max_fbr_dl`, must not be `None`")  # noqa: E501

        self._max_fbr_dl = max_fbr_dl

    @property
    def max_fbr_ul(self):
        """Gets the max_fbr_ul of this GbrQosFlowInformation.


        :return: The max_fbr_ul of this GbrQosFlowInformation.
        :rtype: BitRate
        """
        return self._max_fbr_ul

    @max_fbr_ul.setter
    def max_fbr_ul(self, max_fbr_ul):
        """Sets the max_fbr_ul of this GbrQosFlowInformation.


        :param max_fbr_ul: The max_fbr_ul of this GbrQosFlowInformation.
        :type max_fbr_ul: BitRate
        """
        if max_fbr_ul is None:
            raise ValueError("Invalid value for `max_fbr_ul`, must not be `None`")  # noqa: E501

        self._max_fbr_ul = max_fbr_ul

    @property
    def gua_fbr_dl(self):
        """Gets the gua_fbr_dl of this GbrQosFlowInformation.


        :return: The gua_fbr_dl of this GbrQosFlowInformation.
        :rtype: BitRate
        """
        return self._gua_fbr_dl

    @gua_fbr_dl.setter
    def gua_fbr_dl(self, gua_fbr_dl):
        """Sets the gua_fbr_dl of this GbrQosFlowInformation.


        :param gua_fbr_dl: The gua_fbr_dl of this GbrQosFlowInformation.
        :type gua_fbr_dl: BitRate
        """
        if gua_fbr_dl is None:
            raise ValueError("Invalid value for `gua_fbr_dl`, must not be `None`")  # noqa: E501

        self._gua_fbr_dl = gua_fbr_dl

    @property
    def gua_fbr_ul(self):
        """Gets the gua_fbr_ul of this GbrQosFlowInformation.


        :return: The gua_fbr_ul of this GbrQosFlowInformation.
        :rtype: BitRate
        """
        return self._gua_fbr_ul

    @gua_fbr_ul.setter
    def gua_fbr_ul(self, gua_fbr_ul):
        """Sets the gua_fbr_ul of this GbrQosFlowInformation.


        :param gua_fbr_ul: The gua_fbr_ul of this GbrQosFlowInformation.
        :type gua_fbr_ul: BitRate
        """
        if gua_fbr_ul is None:
            raise ValueError("Invalid value for `gua_fbr_ul`, must not be `None`")  # noqa: E501

        self._gua_fbr_ul = gua_fbr_ul

    @property
    def notif_control(self):
        """Gets the notif_control of this GbrQosFlowInformation.


        :return: The notif_control of this GbrQosFlowInformation.
        :rtype: NotificationControl
        """
        return self._notif_control

    @notif_control.setter
    def notif_control(self, notif_control):
        """Sets the notif_control of this GbrQosFlowInformation.


        :param notif_control: The notif_control of this GbrQosFlowInformation.
        :type notif_control: NotificationControl
        """

        self._notif_control = notif_control

    @property
    def max_packet_loss_rate_dl(self):
        """Gets the max_packet_loss_rate_dl of this GbrQosFlowInformation.


        :return: The max_packet_loss_rate_dl of this GbrQosFlowInformation.
        :rtype: PacketLossRate
        """
        return self._max_packet_loss_rate_dl

    @max_packet_loss_rate_dl.setter
    def max_packet_loss_rate_dl(self, max_packet_loss_rate_dl):
        """Sets the max_packet_loss_rate_dl of this GbrQosFlowInformation.


        :param max_packet_loss_rate_dl: The max_packet_loss_rate_dl of this GbrQosFlowInformation.
        :type max_packet_loss_rate_dl: PacketLossRate
        """

        self._max_packet_loss_rate_dl = max_packet_loss_rate_dl

    @property
    def max_packet_loss_rate_ul(self):
        """Gets the max_packet_loss_rate_ul of this GbrQosFlowInformation.


        :return: The max_packet_loss_rate_ul of this GbrQosFlowInformation.
        :rtype: PacketLossRate
        """
        return self._max_packet_loss_rate_ul

    @max_packet_loss_rate_ul.setter
    def max_packet_loss_rate_ul(self, max_packet_loss_rate_ul):
        """Sets the max_packet_loss_rate_ul of this GbrQosFlowInformation.


        :param max_packet_loss_rate_ul: The max_packet_loss_rate_ul of this GbrQosFlowInformation.
        :type max_packet_loss_rate_ul: PacketLossRate
        """

        self._max_packet_loss_rate_ul = max_packet_loss_rate_ul
