# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.pdu_session_created_data import PduSessionCreatedData  # noqa: F401,E501
from swagger_server import util


class InlineResponse2011(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, json_data=None, binary_data_n1_sm_info_to_ue=None):  # noqa: E501
        """InlineResponse2011 - a model defined in Swagger

        :param json_data: The json_data of this InlineResponse2011.  # noqa: E501
        :type json_data: PduSessionCreatedData
        :param binary_data_n1_sm_info_to_ue: The binary_data_n1_sm_info_to_ue of this InlineResponse2011.  # noqa: E501
        :type binary_data_n1_sm_info_to_ue: str
        """
        self.swagger_types = {
            'json_data': PduSessionCreatedData,
            'binary_data_n1_sm_info_to_ue': str
        }

        self.attribute_map = {
            'json_data': 'jsonData',
            'binary_data_n1_sm_info_to_ue': 'binaryDataN1SmInfoToUe'
        }
        self._json_data = json_data
        self._binary_data_n1_sm_info_to_ue = binary_data_n1_sm_info_to_ue

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201_1 of this InlineResponse2011.  # noqa: E501
        :rtype: InlineResponse2011
        """
        return util.deserialize_model(dikt, cls)

    @property
    def json_data(self):
        """Gets the json_data of this InlineResponse2011.


        :return: The json_data of this InlineResponse2011.
        :rtype: PduSessionCreatedData
        """
        return self._json_data

    @json_data.setter
    def json_data(self, json_data):
        """Sets the json_data of this InlineResponse2011.


        :param json_data: The json_data of this InlineResponse2011.
        :type json_data: PduSessionCreatedData
        """

        self._json_data = json_data

    @property
    def binary_data_n1_sm_info_to_ue(self):
        """Gets the binary_data_n1_sm_info_to_ue of this InlineResponse2011.


        :return: The binary_data_n1_sm_info_to_ue of this InlineResponse2011.
        :rtype: str
        """
        return self._binary_data_n1_sm_info_to_ue

    @binary_data_n1_sm_info_to_ue.setter
    def binary_data_n1_sm_info_to_ue(self, binary_data_n1_sm_info_to_ue):
        """Sets the binary_data_n1_sm_info_to_ue of this InlineResponse2011.


        :param binary_data_n1_sm_info_to_ue: The binary_data_n1_sm_info_to_ue of this InlineResponse2011.
        :type binary_data_n1_sm_info_to_ue: str
        """

        self._binary_data_n1_sm_info_to_ue = binary_data_n1_sm_info_to_ue
