# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ipv4_addr import Ipv4Addr  # noqa: F401,E501
from swagger_server.models.ipv6_addr import Ipv6Addr  # noqa: F401,E501
from swagger_server.models.tai import Tai  # noqa: F401,E501
from swagger_server.models.uinteger import Uinteger  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class N3gaLocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, n3gpp_tai=None, n3_iwf_id=None, ue_ipv4_addr=None, ue_ipv6_addr=None, port_number=None):  # noqa: E501
        """N3gaLocation - a model defined in Swagger

        :param n3gpp_tai: The n3gpp_tai of this N3gaLocation.  # noqa: E501
        :type n3gpp_tai: Tai
        :param n3_iwf_id: The n3_iwf_id of this N3gaLocation.  # noqa: E501
        :type n3_iwf_id: str
        :param ue_ipv4_addr: The ue_ipv4_addr of this N3gaLocation.  # noqa: E501
        :type ue_ipv4_addr: Ipv4Addr
        :param ue_ipv6_addr: The ue_ipv6_addr of this N3gaLocation.  # noqa: E501
        :type ue_ipv6_addr: Ipv6Addr
        :param port_number: The port_number of this N3gaLocation.  # noqa: E501
        :type port_number: Uinteger
        """
        self.swagger_types = {
            'n3gpp_tai': Tai,
            'n3_iwf_id': str,
            'ue_ipv4_addr': Ipv4Addr,
            'ue_ipv6_addr': Ipv6Addr,
            'port_number': Uinteger
        }

        self.attribute_map = {
            'n3gpp_tai': 'n3gppTai',
            'n3_iwf_id': 'n3IwfId',
            'ue_ipv4_addr': 'ueIpv4Addr',
            'ue_ipv6_addr': 'ueIpv6Addr',
            'port_number': 'portNumber'
        }
        self._n3gpp_tai = n3gpp_tai
        self._n3_iwf_id = n3_iwf_id
        self._ue_ipv4_addr = ue_ipv4_addr
        self._ue_ipv6_addr = ue_ipv6_addr
        self._port_number = port_number

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The N3gaLocation of this N3gaLocation.  # noqa: E501
        :rtype: N3gaLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def n3gpp_tai(self):
        """Gets the n3gpp_tai of this N3gaLocation.


        :return: The n3gpp_tai of this N3gaLocation.
        :rtype: Tai
        """
        return self._n3gpp_tai

    @n3gpp_tai.setter
    def n3gpp_tai(self, n3gpp_tai):
        """Sets the n3gpp_tai of this N3gaLocation.


        :param n3gpp_tai: The n3gpp_tai of this N3gaLocation.
        :type n3gpp_tai: Tai
        """

        self._n3gpp_tai = n3gpp_tai

    @property
    def n3_iwf_id(self):
        """Gets the n3_iwf_id of this N3gaLocation.


        :return: The n3_iwf_id of this N3gaLocation.
        :rtype: str
        """
        return self._n3_iwf_id

    @n3_iwf_id.setter
    def n3_iwf_id(self, n3_iwf_id):
        """Sets the n3_iwf_id of this N3gaLocation.


        :param n3_iwf_id: The n3_iwf_id of this N3gaLocation.
        :type n3_iwf_id: str
        """

        self._n3_iwf_id = n3_iwf_id

    @property
    def ue_ipv4_addr(self):
        """Gets the ue_ipv4_addr of this N3gaLocation.


        :return: The ue_ipv4_addr of this N3gaLocation.
        :rtype: Ipv4Addr
        """
        return self._ue_ipv4_addr

    @ue_ipv4_addr.setter
    def ue_ipv4_addr(self, ue_ipv4_addr):
        """Sets the ue_ipv4_addr of this N3gaLocation.


        :param ue_ipv4_addr: The ue_ipv4_addr of this N3gaLocation.
        :type ue_ipv4_addr: Ipv4Addr
        """

        self._ue_ipv4_addr = ue_ipv4_addr

    @property
    def ue_ipv6_addr(self):
        """Gets the ue_ipv6_addr of this N3gaLocation.


        :return: The ue_ipv6_addr of this N3gaLocation.
        :rtype: Ipv6Addr
        """
        return self._ue_ipv6_addr

    @ue_ipv6_addr.setter
    def ue_ipv6_addr(self, ue_ipv6_addr):
        """Sets the ue_ipv6_addr of this N3gaLocation.


        :param ue_ipv6_addr: The ue_ipv6_addr of this N3gaLocation.
        :type ue_ipv6_addr: Ipv6Addr
        """

        self._ue_ipv6_addr = ue_ipv6_addr

    @property
    def port_number(self):
        """Gets the port_number of this N3gaLocation.


        :return: The port_number of this N3gaLocation.
        :rtype: Uinteger
        """
        return self._port_number

    @port_number.setter
    def port_number(self, port_number):
        """Sets the port_number of this N3gaLocation.


        :param port_number: The port_number of this N3gaLocation.
        :type port_number: Uinteger
        """

        self._port_number = port_number
