# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.aver_window import AverWindow  # noqa: F401,E501
from swagger_server.models.max_data_burst_vol import MaxDataBurstVol  # noqa: F401,E501
from swagger_server.models.model5_qi_priority_level import Model5QiPriorityLevel  # noqa: F401,E501
from swagger_server import util


class NonDynamic5Qi(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, priority_level=None, aver_window=None, max_data_burst_vol=None):  # noqa: E501
        """NonDynamic5Qi - a model defined in Swagger

        :param priority_level: The priority_level of this NonDynamic5Qi.  # noqa: E501
        :type priority_level: Model5QiPriorityLevel
        :param aver_window: The aver_window of this NonDynamic5Qi.  # noqa: E501
        :type aver_window: AverWindow
        :param max_data_burst_vol: The max_data_burst_vol of this NonDynamic5Qi.  # noqa: E501
        :type max_data_burst_vol: MaxDataBurstVol
        """
        self.swagger_types = {
            'priority_level': Model5QiPriorityLevel,
            'aver_window': AverWindow,
            'max_data_burst_vol': MaxDataBurstVol
        }

        self.attribute_map = {
            'priority_level': 'priorityLevel',
            'aver_window': 'averWindow',
            'max_data_burst_vol': 'maxDataBurstVol'
        }
        self._priority_level = priority_level
        self._aver_window = aver_window
        self._max_data_burst_vol = max_data_burst_vol

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NonDynamic5Qi of this NonDynamic5Qi.  # noqa: E501
        :rtype: NonDynamic5Qi
        """
        return util.deserialize_model(dikt, cls)

    @property
    def priority_level(self):
        """Gets the priority_level of this NonDynamic5Qi.


        :return: The priority_level of this NonDynamic5Qi.
        :rtype: Model5QiPriorityLevel
        """
        return self._priority_level

    @priority_level.setter
    def priority_level(self, priority_level):
        """Sets the priority_level of this NonDynamic5Qi.


        :param priority_level: The priority_level of this NonDynamic5Qi.
        :type priority_level: Model5QiPriorityLevel
        """

        self._priority_level = priority_level

    @property
    def aver_window(self):
        """Gets the aver_window of this NonDynamic5Qi.


        :return: The aver_window of this NonDynamic5Qi.
        :rtype: AverWindow
        """
        return self._aver_window

    @aver_window.setter
    def aver_window(self, aver_window):
        """Sets the aver_window of this NonDynamic5Qi.


        :param aver_window: The aver_window of this NonDynamic5Qi.
        :type aver_window: AverWindow
        """

        self._aver_window = aver_window

    @property
    def max_data_burst_vol(self):
        """Gets the max_data_burst_vol of this NonDynamic5Qi.


        :return: The max_data_burst_vol of this NonDynamic5Qi.
        :rtype: MaxDataBurstVol
        """
        return self._max_data_burst_vol

    @max_data_burst_vol.setter
    def max_data_burst_vol(self, max_data_burst_vol):
        """Sets the max_data_burst_vol of this NonDynamic5Qi.


        :param max_data_burst_vol: The max_data_burst_vol of this NonDynamic5Qi.
        :type max_data_burst_vol: MaxDataBurstVol
        """

        self._max_data_burst_vol = max_data_burst_vol
