# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.duration_sec import DurationSec  # noqa: F401,E501
from swagger_server.models.problem_details import ProblemDetails  # noqa: F401,E501
from swagger_server.models.ref_to_binary_data import RefToBinaryData  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class PduSessionCreateError(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error=None, n1sm_cause=None, n1_sm_info_to_ue=None, back_off_timer=None, recovery_time=None):  # noqa: E501
        """PduSessionCreateError - a model defined in Swagger

        :param error: The error of this PduSessionCreateError.  # noqa: E501
        :type error: ProblemDetails
        :param n1sm_cause: The n1sm_cause of this PduSessionCreateError.  # noqa: E501
        :type n1sm_cause: str
        :param n1_sm_info_to_ue: The n1_sm_info_to_ue of this PduSessionCreateError.  # noqa: E501
        :type n1_sm_info_to_ue: RefToBinaryData
        :param back_off_timer: The back_off_timer of this PduSessionCreateError.  # noqa: E501
        :type back_off_timer: DurationSec
        :param recovery_time: The recovery_time of this PduSessionCreateError.  # noqa: E501
        :type recovery_time: datetime
        """
        self.swagger_types = {
            'error': ProblemDetails,
            'n1sm_cause': str,
            'n1_sm_info_to_ue': RefToBinaryData,
            'back_off_timer': DurationSec,
            'recovery_time': datetime
        }

        self.attribute_map = {
            'error': 'error',
            'n1sm_cause': 'n1smCause',
            'n1_sm_info_to_ue': 'n1SmInfoToUe',
            'back_off_timer': 'backOffTimer',
            'recovery_time': 'recoveryTime'
        }
        self._error = error
        self._n1sm_cause = n1sm_cause
        self._n1_sm_info_to_ue = n1_sm_info_to_ue
        self._back_off_timer = back_off_timer
        self._recovery_time = recovery_time

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PduSessionCreateError of this PduSessionCreateError.  # noqa: E501
        :rtype: PduSessionCreateError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self):
        """Gets the error of this PduSessionCreateError.


        :return: The error of this PduSessionCreateError.
        :rtype: ProblemDetails
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this PduSessionCreateError.


        :param error: The error of this PduSessionCreateError.
        :type error: ProblemDetails
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error

    @property
    def n1sm_cause(self):
        """Gets the n1sm_cause of this PduSessionCreateError.


        :return: The n1sm_cause of this PduSessionCreateError.
        :rtype: str
        """
        return self._n1sm_cause

    @n1sm_cause.setter
    def n1sm_cause(self, n1sm_cause):
        """Sets the n1sm_cause of this PduSessionCreateError.


        :param n1sm_cause: The n1sm_cause of this PduSessionCreateError.
        :type n1sm_cause: str
        """

        self._n1sm_cause = n1sm_cause

    @property
    def n1_sm_info_to_ue(self):
        """Gets the n1_sm_info_to_ue of this PduSessionCreateError.


        :return: The n1_sm_info_to_ue of this PduSessionCreateError.
        :rtype: RefToBinaryData
        """
        return self._n1_sm_info_to_ue

    @n1_sm_info_to_ue.setter
    def n1_sm_info_to_ue(self, n1_sm_info_to_ue):
        """Sets the n1_sm_info_to_ue of this PduSessionCreateError.


        :param n1_sm_info_to_ue: The n1_sm_info_to_ue of this PduSessionCreateError.
        :type n1_sm_info_to_ue: RefToBinaryData
        """

        self._n1_sm_info_to_ue = n1_sm_info_to_ue

    @property
    def back_off_timer(self):
        """Gets the back_off_timer of this PduSessionCreateError.


        :return: The back_off_timer of this PduSessionCreateError.
        :rtype: DurationSec
        """
        return self._back_off_timer

    @back_off_timer.setter
    def back_off_timer(self, back_off_timer):
        """Sets the back_off_timer of this PduSessionCreateError.


        :param back_off_timer: The back_off_timer of this PduSessionCreateError.
        :type back_off_timer: DurationSec
        """

        self._back_off_timer = back_off_timer

    @property
    def recovery_time(self):
        """Gets the recovery_time of this PduSessionCreateError.


        :return: The recovery_time of this PduSessionCreateError.
        :rtype: datetime
        """
        return self._recovery_time

    @recovery_time.setter
    def recovery_time(self, recovery_time):
        """Sets the recovery_time of this PduSessionCreateError.


        :param recovery_time: The recovery_time of this PduSessionCreateError.
        :type recovery_time: datetime
        """

        self._recovery_time = recovery_time
