# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.notification_cause import NotificationCause  # noqa: F401,E501
from swagger_server import util


class PduSessionNotifyItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, notification_cause=None):  # noqa: E501
        """PduSessionNotifyItem - a model defined in Swagger

        :param notification_cause: The notification_cause of this PduSessionNotifyItem.  # noqa: E501
        :type notification_cause: NotificationCause
        """
        self.swagger_types = {
            'notification_cause': NotificationCause
        }

        self.attribute_map = {
            'notification_cause': 'notificationCause'
        }
        self._notification_cause = notification_cause

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PduSessionNotifyItem of this PduSessionNotifyItem.  # noqa: E501
        :rtype: PduSessionNotifyItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_cause(self):
        """Gets the notification_cause of this PduSessionNotifyItem.


        :return: The notification_cause of this PduSessionNotifyItem.
        :rtype: NotificationCause
        """
        return self._notification_cause

    @notification_cause.setter
    def notification_cause(self, notification_cause):
        """Sets the notification_cause of this PduSessionNotifyItem.


        :param notification_cause: The notification_cause of this PduSessionNotifyItem.
        :type notification_cause: NotificationCause
        """
        if notification_cause is None:
            raise ValueError("Invalid value for `notification_cause`, must not be `None`")  # noqa: E501

        self._notification_cause = notification_cause
