# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.bytes import Bytes  # noqa: F401,E501
from swagger_server.models.eps_bearer_id import EpsBearerId  # noqa: F401,E501
from swagger_server.models.qfi import Qfi  # noqa: F401,E501
from swagger_server.models.qos_flow_profile import QosFlowProfile  # noqa: F401,E501
from swagger_server import util


class QosFlowSetupItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, qfi=None, qos_rules=None, ebi=None, qos_flow_description=None, qos_flow_profile=None):  # noqa: E501
        """QosFlowSetupItem - a model defined in Swagger

        :param qfi: The qfi of this QosFlowSetupItem.  # noqa: E501
        :type qfi: Qfi
        :param qos_rules: The qos_rules of this QosFlowSetupItem.  # noqa: E501
        :type qos_rules: Bytes
        :param ebi: The ebi of this QosFlowSetupItem.  # noqa: E501
        :type ebi: EpsBearerId
        :param qos_flow_description: The qos_flow_description of this QosFlowSetupItem.  # noqa: E501
        :type qos_flow_description: Bytes
        :param qos_flow_profile: The qos_flow_profile of this QosFlowSetupItem.  # noqa: E501
        :type qos_flow_profile: QosFlowProfile
        """
        self.swagger_types = {
            'qfi': Qfi,
            'qos_rules': Bytes,
            'ebi': EpsBearerId,
            'qos_flow_description': Bytes,
            'qos_flow_profile': QosFlowProfile
        }

        self.attribute_map = {
            'qfi': 'qfi',
            'qos_rules': 'qosRules',
            'ebi': 'ebi',
            'qos_flow_description': 'qosFlowDescription',
            'qos_flow_profile': 'qosFlowProfile'
        }
        self._qfi = qfi
        self._qos_rules = qos_rules
        self._ebi = ebi
        self._qos_flow_description = qos_flow_description
        self._qos_flow_profile = qos_flow_profile

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QosFlowSetupItem of this QosFlowSetupItem.  # noqa: E501
        :rtype: QosFlowSetupItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def qfi(self):
        """Gets the qfi of this QosFlowSetupItem.


        :return: The qfi of this QosFlowSetupItem.
        :rtype: Qfi
        """
        return self._qfi

    @qfi.setter
    def qfi(self, qfi):
        """Sets the qfi of this QosFlowSetupItem.


        :param qfi: The qfi of this QosFlowSetupItem.
        :type qfi: Qfi
        """
        if qfi is None:
            raise ValueError("Invalid value for `qfi`, must not be `None`")  # noqa: E501

        self._qfi = qfi

    @property
    def qos_rules(self):
        """Gets the qos_rules of this QosFlowSetupItem.


        :return: The qos_rules of this QosFlowSetupItem.
        :rtype: Bytes
        """
        return self._qos_rules

    @qos_rules.setter
    def qos_rules(self, qos_rules):
        """Sets the qos_rules of this QosFlowSetupItem.


        :param qos_rules: The qos_rules of this QosFlowSetupItem.
        :type qos_rules: Bytes
        """
        if qos_rules is None:
            raise ValueError("Invalid value for `qos_rules`, must not be `None`")  # noqa: E501

        self._qos_rules = qos_rules

    @property
    def ebi(self):
        """Gets the ebi of this QosFlowSetupItem.


        :return: The ebi of this QosFlowSetupItem.
        :rtype: EpsBearerId
        """
        return self._ebi

    @ebi.setter
    def ebi(self, ebi):
        """Sets the ebi of this QosFlowSetupItem.


        :param ebi: The ebi of this QosFlowSetupItem.
        :type ebi: EpsBearerId
        """

        self._ebi = ebi

    @property
    def qos_flow_description(self):
        """Gets the qos_flow_description of this QosFlowSetupItem.


        :return: The qos_flow_description of this QosFlowSetupItem.
        :rtype: Bytes
        """
        return self._qos_flow_description

    @qos_flow_description.setter
    def qos_flow_description(self, qos_flow_description):
        """Sets the qos_flow_description of this QosFlowSetupItem.


        :param qos_flow_description: The qos_flow_description of this QosFlowSetupItem.
        :type qos_flow_description: Bytes
        """

        self._qos_flow_description = qos_flow_description

    @property
    def qos_flow_profile(self):
        """Gets the qos_flow_profile of this QosFlowSetupItem.


        :return: The qos_flow_profile of this QosFlowSetupItem.
        :rtype: QosFlowProfile
        """
        return self._qos_flow_profile

    @qos_flow_profile.setter
    def qos_flow_profile(self, qos_flow_profile):
        """Sets the qos_flow_profile of this QosFlowSetupItem.


        :param qos_flow_profile: The qos_flow_profile of this QosFlowSetupItem.
        :type qos_flow_profile: QosFlowProfile
        """

        self._qos_flow_profile = qos_flow_profile
