# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cause import Cause  # noqa: F401,E501
from swagger_server.models.qfi import Qfi  # noqa: F401,E501
from swagger_server import util


class QosFlowItem(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, qfi=None, cause=None):  # noqa: E501
        """QosFlowItem - a model defined in Swagger

        :param qfi: The qfi of this QosFlowItem.  # noqa: E501
        :type qfi: Qfi
        :param cause: The cause of this QosFlowItem.  # noqa: E501
        :type cause: Cause
        """
        self.swagger_types = {
            'qfi': Qfi,
            'cause': Cause
        }

        self.attribute_map = {
            'qfi': 'qfi',
            'cause': 'cause'
        }
        self._qfi = qfi
        self._cause = cause

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QosFlowItem of this QosFlowItem.  # noqa: E501
        :rtype: QosFlowItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def qfi(self):
        """Gets the qfi of this QosFlowItem.


        :return: The qfi of this QosFlowItem.
        :rtype: Qfi
        """
        return self._qfi

    @qfi.setter
    def qfi(self, qfi):
        """Sets the qfi of this QosFlowItem.


        :param qfi: The qfi of this QosFlowItem.
        :type qfi: Qfi
        """
        if qfi is None:
            raise ValueError("Invalid value for `qfi`, must not be `None`")  # noqa: E501

        self._qfi = qfi

    @property
    def cause(self):
        """Gets the cause of this QosFlowItem.


        :return: The cause of this QosFlowItem.
        :rtype: Cause
        """
        return self._cause

    @cause.setter
    def cause(self, cause):
        """Sets the cause of this QosFlowItem.


        :param cause: The cause of this QosFlowItem.
        :type cause: Cause
        """

        self._cause = cause
