# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cause import Cause  # noqa: F401,E501
from swagger_server.models.model5_g_mm_cause import Model5GMmCause  # noqa: F401,E501
from swagger_server.models.ng_ap_cause import NgApCause  # noqa: F401,E501
from swagger_server.models.secondary_rat_usage_info import SecondaryRatUsageInfo  # noqa: F401,E501
from swagger_server.models.secondary_rat_usage_report import SecondaryRatUsageReport  # noqa: F401,E501
from swagger_server.models.time_zone import TimeZone  # noqa: F401,E501
from swagger_server.models.user_location import UserLocation  # noqa: F401,E501
from swagger_server import util


class ReleaseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cause=None, ng_ap_cause=None, _5g_mm_cause_value=None, ue_location=None, ue_time_zone=None, add_ue_location=None, secondary_rat_usage_report=None, secondary_rat_usage_info=None):  # noqa: E501
        """ReleaseData - a model defined in Swagger

        :param cause: The cause of this ReleaseData.  # noqa: E501
        :type cause: Cause
        :param ng_ap_cause: The ng_ap_cause of this ReleaseData.  # noqa: E501
        :type ng_ap_cause: NgApCause
        :param _5g_mm_cause_value: The _5g_mm_cause_value of this ReleaseData.  # noqa: E501
        :type _5g_mm_cause_value: Model5GMmCause
        :param ue_location: The ue_location of this ReleaseData.  # noqa: E501
        :type ue_location: UserLocation
        :param ue_time_zone: The ue_time_zone of this ReleaseData.  # noqa: E501
        :type ue_time_zone: TimeZone
        :param add_ue_location: The add_ue_location of this ReleaseData.  # noqa: E501
        :type add_ue_location: UserLocation
        :param secondary_rat_usage_report: The secondary_rat_usage_report of this ReleaseData.  # noqa: E501
        :type secondary_rat_usage_report: List[SecondaryRatUsageReport]
        :param secondary_rat_usage_info: The secondary_rat_usage_info of this ReleaseData.  # noqa: E501
        :type secondary_rat_usage_info: List[SecondaryRatUsageInfo]
        """
        self.swagger_types = {
            'cause': Cause,
            'ng_ap_cause': NgApCause,
            '_5g_mm_cause_value': Model5GMmCause,
            'ue_location': UserLocation,
            'ue_time_zone': TimeZone,
            'add_ue_location': UserLocation,
            'secondary_rat_usage_report': List[SecondaryRatUsageReport],
            'secondary_rat_usage_info': List[SecondaryRatUsageInfo]
        }

        self.attribute_map = {
            'cause': 'cause',
            'ng_ap_cause': 'ngApCause',
            '_5g_mm_cause_value': '5gMmCauseValue',
            'ue_location': 'ueLocation',
            'ue_time_zone': 'ueTimeZone',
            'add_ue_location': 'addUeLocation',
            'secondary_rat_usage_report': 'secondaryRatUsageReport',
            'secondary_rat_usage_info': 'secondaryRatUsageInfo'
        }
        self._cause = cause
        self._ng_ap_cause = ng_ap_cause
        self.__5g_mm_cause_value = _5g_mm_cause_value
        self._ue_location = ue_location
        self._ue_time_zone = ue_time_zone
        self._add_ue_location = add_ue_location
        self._secondary_rat_usage_report = secondary_rat_usage_report
        self._secondary_rat_usage_info = secondary_rat_usage_info

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ReleaseData of this ReleaseData.  # noqa: E501
        :rtype: ReleaseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cause(self):
        """Gets the cause of this ReleaseData.


        :return: The cause of this ReleaseData.
        :rtype: Cause
        """
        return self._cause

    @cause.setter
    def cause(self, cause):
        """Sets the cause of this ReleaseData.


        :param cause: The cause of this ReleaseData.
        :type cause: Cause
        """

        self._cause = cause

    @property
    def ng_ap_cause(self):
        """Gets the ng_ap_cause of this ReleaseData.


        :return: The ng_ap_cause of this ReleaseData.
        :rtype: NgApCause
        """
        return self._ng_ap_cause

    @ng_ap_cause.setter
    def ng_ap_cause(self, ng_ap_cause):
        """Sets the ng_ap_cause of this ReleaseData.


        :param ng_ap_cause: The ng_ap_cause of this ReleaseData.
        :type ng_ap_cause: NgApCause
        """

        self._ng_ap_cause = ng_ap_cause

    @property
    def _5g_mm_cause_value(self):
        """Gets the _5g_mm_cause_value of this ReleaseData.


        :return: The _5g_mm_cause_value of this ReleaseData.
        :rtype: Model5GMmCause
        """
        return self.__5g_mm_cause_value

    @_5g_mm_cause_value.setter
    def _5g_mm_cause_value(self, _5g_mm_cause_value):
        """Sets the _5g_mm_cause_value of this ReleaseData.


        :param _5g_mm_cause_value: The _5g_mm_cause_value of this ReleaseData.
        :type _5g_mm_cause_value: Model5GMmCause
        """

        self.__5g_mm_cause_value = _5g_mm_cause_value

    @property
    def ue_location(self):
        """Gets the ue_location of this ReleaseData.


        :return: The ue_location of this ReleaseData.
        :rtype: UserLocation
        """
        return self._ue_location

    @ue_location.setter
    def ue_location(self, ue_location):
        """Sets the ue_location of this ReleaseData.


        :param ue_location: The ue_location of this ReleaseData.
        :type ue_location: UserLocation
        """

        self._ue_location = ue_location

    @property
    def ue_time_zone(self):
        """Gets the ue_time_zone of this ReleaseData.


        :return: The ue_time_zone of this ReleaseData.
        :rtype: TimeZone
        """
        return self._ue_time_zone

    @ue_time_zone.setter
    def ue_time_zone(self, ue_time_zone):
        """Sets the ue_time_zone of this ReleaseData.


        :param ue_time_zone: The ue_time_zone of this ReleaseData.
        :type ue_time_zone: TimeZone
        """

        self._ue_time_zone = ue_time_zone

    @property
    def add_ue_location(self):
        """Gets the add_ue_location of this ReleaseData.


        :return: The add_ue_location of this ReleaseData.
        :rtype: UserLocation
        """
        return self._add_ue_location

    @add_ue_location.setter
    def add_ue_location(self, add_ue_location):
        """Sets the add_ue_location of this ReleaseData.


        :param add_ue_location: The add_ue_location of this ReleaseData.
        :type add_ue_location: UserLocation
        """

        self._add_ue_location = add_ue_location

    @property
    def secondary_rat_usage_report(self):
        """Gets the secondary_rat_usage_report of this ReleaseData.


        :return: The secondary_rat_usage_report of this ReleaseData.
        :rtype: List[SecondaryRatUsageReport]
        """
        return self._secondary_rat_usage_report

    @secondary_rat_usage_report.setter
    def secondary_rat_usage_report(self, secondary_rat_usage_report):
        """Sets the secondary_rat_usage_report of this ReleaseData.


        :param secondary_rat_usage_report: The secondary_rat_usage_report of this ReleaseData.
        :type secondary_rat_usage_report: List[SecondaryRatUsageReport]
        """

        self._secondary_rat_usage_report = secondary_rat_usage_report

    @property
    def secondary_rat_usage_info(self):
        """Gets the secondary_rat_usage_info of this ReleaseData.


        :return: The secondary_rat_usage_info of this ReleaseData.
        :rtype: List[SecondaryRatUsageInfo]
        """
        return self._secondary_rat_usage_info

    @secondary_rat_usage_info.setter
    def secondary_rat_usage_info(self, secondary_rat_usage_info):
        """Sets the secondary_rat_usage_info of this ReleaseData.


        :param secondary_rat_usage_info: The secondary_rat_usage_info of this ReleaseData.
        :type secondary_rat_usage_info: List[SecondaryRatUsageInfo]
        """

        self._secondary_rat_usage_info = secondary_rat_usage_info
