# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.partial_record_method import PartialRecordMethod  # noqa: F401,E501
from swagger_server.models.trigger import Trigger  # noqa: F401,E501
from swagger_server import util


class RoamingChargingProfile(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, triggers=None, partial_record_method=None):  # noqa: E501
        """RoamingChargingProfile - a model defined in Swagger

        :param triggers: The triggers of this RoamingChargingProfile.  # noqa: E501
        :type triggers: List[Trigger]
        :param partial_record_method: The partial_record_method of this RoamingChargingProfile.  # noqa: E501
        :type partial_record_method: PartialRecordMethod
        """
        self.swagger_types = {
            'triggers': List[Trigger],
            'partial_record_method': PartialRecordMethod
        }

        self.attribute_map = {
            'triggers': 'triggers',
            'partial_record_method': 'partialRecordMethod'
        }
        self._triggers = triggers
        self._partial_record_method = partial_record_method

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RoamingChargingProfile of this RoamingChargingProfile.  # noqa: E501
        :rtype: RoamingChargingProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def triggers(self):
        """Gets the triggers of this RoamingChargingProfile.


        :return: The triggers of this RoamingChargingProfile.
        :rtype: List[Trigger]
        """
        return self._triggers

    @triggers.setter
    def triggers(self, triggers):
        """Sets the triggers of this RoamingChargingProfile.


        :param triggers: The triggers of this RoamingChargingProfile.
        :type triggers: List[Trigger]
        """

        self._triggers = triggers

    @property
    def partial_record_method(self):
        """Gets the partial_record_method of this RoamingChargingProfile.


        :return: The partial_record_method of this RoamingChargingProfile.
        :rtype: PartialRecordMethod
        """
        return self._partial_record_method

    @partial_record_method.setter
    def partial_record_method(self, partial_record_method):
        """Sets the partial_record_method of this RoamingChargingProfile.


        :param partial_record_method: The partial_record_method of this RoamingChargingProfile.
        :type partial_record_method: PartialRecordMethod
        """

        self._partial_record_method = partial_record_method
