# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.qos_flow_usage_report import QosFlowUsageReport  # noqa: F401,E501
from swagger_server.models.rat_type import RatType  # noqa: F401,E501
from swagger_server.models.volume_timed_report import VolumeTimedReport  # noqa: F401,E501
from swagger_server import util


class SecondaryRatUsageInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, secondary_rat_type=None, qos_flows_usage_data=None, pdu_session_usage_data=None):  # noqa: E501
        """SecondaryRatUsageInfo - a model defined in Swagger

        :param secondary_rat_type: The secondary_rat_type of this SecondaryRatUsageInfo.  # noqa: E501
        :type secondary_rat_type: RatType
        :param qos_flows_usage_data: The qos_flows_usage_data of this SecondaryRatUsageInfo.  # noqa: E501
        :type qos_flows_usage_data: List[QosFlowUsageReport]
        :param pdu_session_usage_data: The pdu_session_usage_data of this SecondaryRatUsageInfo.  # noqa: E501
        :type pdu_session_usage_data: List[VolumeTimedReport]
        """
        self.swagger_types = {
            'secondary_rat_type': RatType,
            'qos_flows_usage_data': List[QosFlowUsageReport],
            'pdu_session_usage_data': List[VolumeTimedReport]
        }

        self.attribute_map = {
            'secondary_rat_type': 'secondaryRatType',
            'qos_flows_usage_data': 'qosFlowsUsageData',
            'pdu_session_usage_data': 'pduSessionUsageData'
        }
        self._secondary_rat_type = secondary_rat_type
        self._qos_flows_usage_data = qos_flows_usage_data
        self._pdu_session_usage_data = pdu_session_usage_data

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SecondaryRatUsageInfo of this SecondaryRatUsageInfo.  # noqa: E501
        :rtype: SecondaryRatUsageInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def secondary_rat_type(self):
        """Gets the secondary_rat_type of this SecondaryRatUsageInfo.


        :return: The secondary_rat_type of this SecondaryRatUsageInfo.
        :rtype: RatType
        """
        return self._secondary_rat_type

    @secondary_rat_type.setter
    def secondary_rat_type(self, secondary_rat_type):
        """Sets the secondary_rat_type of this SecondaryRatUsageInfo.


        :param secondary_rat_type: The secondary_rat_type of this SecondaryRatUsageInfo.
        :type secondary_rat_type: RatType
        """
        if secondary_rat_type is None:
            raise ValueError("Invalid value for `secondary_rat_type`, must not be `None`")  # noqa: E501

        self._secondary_rat_type = secondary_rat_type

    @property
    def qos_flows_usage_data(self):
        """Gets the qos_flows_usage_data of this SecondaryRatUsageInfo.


        :return: The qos_flows_usage_data of this SecondaryRatUsageInfo.
        :rtype: List[QosFlowUsageReport]
        """
        return self._qos_flows_usage_data

    @qos_flows_usage_data.setter
    def qos_flows_usage_data(self, qos_flows_usage_data):
        """Sets the qos_flows_usage_data of this SecondaryRatUsageInfo.


        :param qos_flows_usage_data: The qos_flows_usage_data of this SecondaryRatUsageInfo.
        :type qos_flows_usage_data: List[QosFlowUsageReport]
        """

        self._qos_flows_usage_data = qos_flows_usage_data

    @property
    def pdu_session_usage_data(self):
        """Gets the pdu_session_usage_data of this SecondaryRatUsageInfo.


        :return: The pdu_session_usage_data of this SecondaryRatUsageInfo.
        :rtype: List[VolumeTimedReport]
        """
        return self._pdu_session_usage_data

    @pdu_session_usage_data.setter
    def pdu_session_usage_data(self, pdu_session_usage_data):
        """Sets the pdu_session_usage_data of this SecondaryRatUsageInfo.


        :param pdu_session_usage_data: The pdu_session_usage_data of this SecondaryRatUsageInfo.
        :type pdu_session_usage_data: List[VolumeTimedReport]
        """

        self._pdu_session_usage_data = pdu_session_usage_data
