# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cause import Cause  # noqa: F401,E501
from swagger_server.models.model5_g_mm_cause import Model5GMmCause  # noqa: F401,E501
from swagger_server.models.n2_sm_info_type import N2SmInfoType  # noqa: F401,E501
from swagger_server.models.ng_ap_cause import NgApCause  # noqa: F401,E501
from swagger_server.models.ref_to_binary_data import RefToBinaryData  # noqa: F401,E501
from swagger_server.models.time_zone import TimeZone  # noqa: F401,E501
from swagger_server.models.user_location import UserLocation  # noqa: F401,E501
from swagger_server import util


class SmContextReleaseData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, cause=None, ng_ap_cause=None, _5g_mm_cause_value=None, ue_location=None, ue_time_zone=None, add_ue_location=None, vsmf_release_only=False, n2_sm_info=None, n2_sm_info_type=None):  # noqa: E501
        """SmContextReleaseData - a model defined in Swagger

        :param cause: The cause of this SmContextReleaseData.  # noqa: E501
        :type cause: Cause
        :param ng_ap_cause: The ng_ap_cause of this SmContextReleaseData.  # noqa: E501
        :type ng_ap_cause: NgApCause
        :param _5g_mm_cause_value: The _5g_mm_cause_value of this SmContextReleaseData.  # noqa: E501
        :type _5g_mm_cause_value: Model5GMmCause
        :param ue_location: The ue_location of this SmContextReleaseData.  # noqa: E501
        :type ue_location: UserLocation
        :param ue_time_zone: The ue_time_zone of this SmContextReleaseData.  # noqa: E501
        :type ue_time_zone: TimeZone
        :param add_ue_location: The add_ue_location of this SmContextReleaseData.  # noqa: E501
        :type add_ue_location: UserLocation
        :param vsmf_release_only: The vsmf_release_only of this SmContextReleaseData.  # noqa: E501
        :type vsmf_release_only: bool
        :param n2_sm_info: The n2_sm_info of this SmContextReleaseData.  # noqa: E501
        :type n2_sm_info: RefToBinaryData
        :param n2_sm_info_type: The n2_sm_info_type of this SmContextReleaseData.  # noqa: E501
        :type n2_sm_info_type: N2SmInfoType
        """
        self.swagger_types = {
            'cause': Cause,
            'ng_ap_cause': NgApCause,
            '_5g_mm_cause_value': Model5GMmCause,
            'ue_location': UserLocation,
            'ue_time_zone': TimeZone,
            'add_ue_location': UserLocation,
            'vsmf_release_only': bool,
            'n2_sm_info': RefToBinaryData,
            'n2_sm_info_type': N2SmInfoType
        }

        self.attribute_map = {
            'cause': 'cause',
            'ng_ap_cause': 'ngApCause',
            '_5g_mm_cause_value': '5gMmCauseValue',
            'ue_location': 'ueLocation',
            'ue_time_zone': 'ueTimeZone',
            'add_ue_location': 'addUeLocation',
            'vsmf_release_only': 'vsmfReleaseOnly',
            'n2_sm_info': 'n2SmInfo',
            'n2_sm_info_type': 'n2SmInfoType'
        }
        self._cause = cause
        self._ng_ap_cause = ng_ap_cause
        self.__5g_mm_cause_value = _5g_mm_cause_value
        self._ue_location = ue_location
        self._ue_time_zone = ue_time_zone
        self._add_ue_location = add_ue_location
        self._vsmf_release_only = vsmf_release_only
        self._n2_sm_info = n2_sm_info
        self._n2_sm_info_type = n2_sm_info_type

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmContextReleaseData of this SmContextReleaseData.  # noqa: E501
        :rtype: SmContextReleaseData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def cause(self):
        """Gets the cause of this SmContextReleaseData.


        :return: The cause of this SmContextReleaseData.
        :rtype: Cause
        """
        return self._cause

    @cause.setter
    def cause(self, cause):
        """Sets the cause of this SmContextReleaseData.


        :param cause: The cause of this SmContextReleaseData.
        :type cause: Cause
        """

        self._cause = cause

    @property
    def ng_ap_cause(self):
        """Gets the ng_ap_cause of this SmContextReleaseData.


        :return: The ng_ap_cause of this SmContextReleaseData.
        :rtype: NgApCause
        """
        return self._ng_ap_cause

    @ng_ap_cause.setter
    def ng_ap_cause(self, ng_ap_cause):
        """Sets the ng_ap_cause of this SmContextReleaseData.


        :param ng_ap_cause: The ng_ap_cause of this SmContextReleaseData.
        :type ng_ap_cause: NgApCause
        """

        self._ng_ap_cause = ng_ap_cause

    @property
    def _5g_mm_cause_value(self):
        """Gets the _5g_mm_cause_value of this SmContextReleaseData.


        :return: The _5g_mm_cause_value of this SmContextReleaseData.
        :rtype: Model5GMmCause
        """
        return self.__5g_mm_cause_value

    @_5g_mm_cause_value.setter
    def _5g_mm_cause_value(self, _5g_mm_cause_value):
        """Sets the _5g_mm_cause_value of this SmContextReleaseData.


        :param _5g_mm_cause_value: The _5g_mm_cause_value of this SmContextReleaseData.
        :type _5g_mm_cause_value: Model5GMmCause
        """

        self.__5g_mm_cause_value = _5g_mm_cause_value

    @property
    def ue_location(self):
        """Gets the ue_location of this SmContextReleaseData.


        :return: The ue_location of this SmContextReleaseData.
        :rtype: UserLocation
        """
        return self._ue_location

    @ue_location.setter
    def ue_location(self, ue_location):
        """Sets the ue_location of this SmContextReleaseData.


        :param ue_location: The ue_location of this SmContextReleaseData.
        :type ue_location: UserLocation
        """

        self._ue_location = ue_location

    @property
    def ue_time_zone(self):
        """Gets the ue_time_zone of this SmContextReleaseData.


        :return: The ue_time_zone of this SmContextReleaseData.
        :rtype: TimeZone
        """
        return self._ue_time_zone

    @ue_time_zone.setter
    def ue_time_zone(self, ue_time_zone):
        """Sets the ue_time_zone of this SmContextReleaseData.


        :param ue_time_zone: The ue_time_zone of this SmContextReleaseData.
        :type ue_time_zone: TimeZone
        """

        self._ue_time_zone = ue_time_zone

    @property
    def add_ue_location(self):
        """Gets the add_ue_location of this SmContextReleaseData.


        :return: The add_ue_location of this SmContextReleaseData.
        :rtype: UserLocation
        """
        return self._add_ue_location

    @add_ue_location.setter
    def add_ue_location(self, add_ue_location):
        """Sets the add_ue_location of this SmContextReleaseData.


        :param add_ue_location: The add_ue_location of this SmContextReleaseData.
        :type add_ue_location: UserLocation
        """

        self._add_ue_location = add_ue_location

    @property
    def vsmf_release_only(self):
        """Gets the vsmf_release_only of this SmContextReleaseData.


        :return: The vsmf_release_only of this SmContextReleaseData.
        :rtype: bool
        """
        return self._vsmf_release_only

    @vsmf_release_only.setter
    def vsmf_release_only(self, vsmf_release_only):
        """Sets the vsmf_release_only of this SmContextReleaseData.


        :param vsmf_release_only: The vsmf_release_only of this SmContextReleaseData.
        :type vsmf_release_only: bool
        """

        self._vsmf_release_only = vsmf_release_only

    @property
    def n2_sm_info(self):
        """Gets the n2_sm_info of this SmContextReleaseData.


        :return: The n2_sm_info of this SmContextReleaseData.
        :rtype: RefToBinaryData
        """
        return self._n2_sm_info

    @n2_sm_info.setter
    def n2_sm_info(self, n2_sm_info):
        """Sets the n2_sm_info of this SmContextReleaseData.


        :param n2_sm_info: The n2_sm_info of this SmContextReleaseData.
        :type n2_sm_info: RefToBinaryData
        """

        self._n2_sm_info = n2_sm_info

    @property
    def n2_sm_info_type(self):
        """Gets the n2_sm_info_type of this SmContextReleaseData.


        :return: The n2_sm_info_type of this SmContextReleaseData.
        :rtype: N2SmInfoType
        """
        return self._n2_sm_info_type

    @n2_sm_info_type.setter
    def n2_sm_info_type(self, n2_sm_info_type):
        """Sets the n2_sm_info_type of this SmContextReleaseData.


        :param n2_sm_info_type: The n2_sm_info_type of this SmContextReleaseData.
        :type n2_sm_info_type: N2SmInfoType
        """

        self._n2_sm_info_type = n2_sm_info_type
