# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.mme_capabilities import MmeCapabilities  # noqa: F401,E501
from swagger_server import util


class SmContextRetrieveData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, target_mme_cap=None):  # noqa: E501
        """SmContextRetrieveData - a model defined in Swagger

        :param target_mme_cap: The target_mme_cap of this SmContextRetrieveData.  # noqa: E501
        :type target_mme_cap: MmeCapabilities
        """
        self.swagger_types = {
            'target_mme_cap': MmeCapabilities
        }

        self.attribute_map = {
            'target_mme_cap': 'targetMmeCap'
        }
        self._target_mme_cap = target_mme_cap

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmContextRetrieveData of this SmContextRetrieveData.  # noqa: E501
        :rtype: SmContextRetrieveData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def target_mme_cap(self):
        """Gets the target_mme_cap of this SmContextRetrieveData.


        :return: The target_mme_cap of this SmContextRetrieveData.
        :rtype: MmeCapabilities
        """
        return self._target_mme_cap

    @target_mme_cap.setter
    def target_mme_cap(self, target_mme_cap):
        """Sets the target_mme_cap of this SmContextRetrieveData.


        :param target_mme_cap: The target_mme_cap of this SmContextRetrieveData.
        :type target_mme_cap: MmeCapabilities
        """

        self._target_mme_cap = target_mme_cap
