# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.eps_bearer_id import EpsBearerId  # noqa: F401,E501
from swagger_server.models.model5_g_mm_cause import Model5GMmCause  # noqa: F401,E501
from swagger_server.models.ng_ap_cause import NgApCause  # noqa: F401,E501
from swagger_server.models.problem_details import ProblemDetails  # noqa: F401,E501
from swagger_server.models.procedure_transaction_id import ProcedureTransactionId  # noqa: F401,E501
from swagger_server.models.ref_to_binary_data import RefToBinaryData  # noqa: F401,E501
import re  # noqa: F401,E501
from swagger_server import util


class VsmfUpdateError(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, error=None, pti=None, n1sm_cause=None, n1_sm_info_from_ue=None, unknown_n1_sm_info=None, failed_to_assign_ebi_list=None, ng_ap_cause=None, _5g_mm_cause_value=None, recovery_time=None):  # noqa: E501
        """VsmfUpdateError - a model defined in Swagger

        :param error: The error of this VsmfUpdateError.  # noqa: E501
        :type error: ProblemDetails
        :param pti: The pti of this VsmfUpdateError.  # noqa: E501
        :type pti: ProcedureTransactionId
        :param n1sm_cause: The n1sm_cause of this VsmfUpdateError.  # noqa: E501
        :type n1sm_cause: str
        :param n1_sm_info_from_ue: The n1_sm_info_from_ue of this VsmfUpdateError.  # noqa: E501
        :type n1_sm_info_from_ue: RefToBinaryData
        :param unknown_n1_sm_info: The unknown_n1_sm_info of this VsmfUpdateError.  # noqa: E501
        :type unknown_n1_sm_info: RefToBinaryData
        :param failed_to_assign_ebi_list: The failed_to_assign_ebi_list of this VsmfUpdateError.  # noqa: E501
        :type failed_to_assign_ebi_list: List[EpsBearerId]
        :param ng_ap_cause: The ng_ap_cause of this VsmfUpdateError.  # noqa: E501
        :type ng_ap_cause: NgApCause
        :param _5g_mm_cause_value: The _5g_mm_cause_value of this VsmfUpdateError.  # noqa: E501
        :type _5g_mm_cause_value: Model5GMmCause
        :param recovery_time: The recovery_time of this VsmfUpdateError.  # noqa: E501
        :type recovery_time: datetime
        """
        self.swagger_types = {
            'error': ProblemDetails,
            'pti': ProcedureTransactionId,
            'n1sm_cause': str,
            'n1_sm_info_from_ue': RefToBinaryData,
            'unknown_n1_sm_info': RefToBinaryData,
            'failed_to_assign_ebi_list': List[EpsBearerId],
            'ng_ap_cause': NgApCause,
            '_5g_mm_cause_value': Model5GMmCause,
            'recovery_time': datetime
        }

        self.attribute_map = {
            'error': 'error',
            'pti': 'pti',
            'n1sm_cause': 'n1smCause',
            'n1_sm_info_from_ue': 'n1SmInfoFromUe',
            'unknown_n1_sm_info': 'unknownN1SmInfo',
            'failed_to_assign_ebi_list': 'failedToAssignEbiList',
            'ng_ap_cause': 'ngApCause',
            '_5g_mm_cause_value': '5gMmCauseValue',
            'recovery_time': 'recoveryTime'
        }
        self._error = error
        self._pti = pti
        self._n1sm_cause = n1sm_cause
        self._n1_sm_info_from_ue = n1_sm_info_from_ue
        self._unknown_n1_sm_info = unknown_n1_sm_info
        self._failed_to_assign_ebi_list = failed_to_assign_ebi_list
        self._ng_ap_cause = ng_ap_cause
        self.__5g_mm_cause_value = _5g_mm_cause_value
        self._recovery_time = recovery_time

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VsmfUpdateError of this VsmfUpdateError.  # noqa: E501
        :rtype: VsmfUpdateError
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self):
        """Gets the error of this VsmfUpdateError.


        :return: The error of this VsmfUpdateError.
        :rtype: ProblemDetails
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this VsmfUpdateError.


        :param error: The error of this VsmfUpdateError.
        :type error: ProblemDetails
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error

    @property
    def pti(self):
        """Gets the pti of this VsmfUpdateError.


        :return: The pti of this VsmfUpdateError.
        :rtype: ProcedureTransactionId
        """
        return self._pti

    @pti.setter
    def pti(self, pti):
        """Sets the pti of this VsmfUpdateError.


        :param pti: The pti of this VsmfUpdateError.
        :type pti: ProcedureTransactionId
        """

        self._pti = pti

    @property
    def n1sm_cause(self):
        """Gets the n1sm_cause of this VsmfUpdateError.


        :return: The n1sm_cause of this VsmfUpdateError.
        :rtype: str
        """
        return self._n1sm_cause

    @n1sm_cause.setter
    def n1sm_cause(self, n1sm_cause):
        """Sets the n1sm_cause of this VsmfUpdateError.


        :param n1sm_cause: The n1sm_cause of this VsmfUpdateError.
        :type n1sm_cause: str
        """

        self._n1sm_cause = n1sm_cause

    @property
    def n1_sm_info_from_ue(self):
        """Gets the n1_sm_info_from_ue of this VsmfUpdateError.


        :return: The n1_sm_info_from_ue of this VsmfUpdateError.
        :rtype: RefToBinaryData
        """
        return self._n1_sm_info_from_ue

    @n1_sm_info_from_ue.setter
    def n1_sm_info_from_ue(self, n1_sm_info_from_ue):
        """Sets the n1_sm_info_from_ue of this VsmfUpdateError.


        :param n1_sm_info_from_ue: The n1_sm_info_from_ue of this VsmfUpdateError.
        :type n1_sm_info_from_ue: RefToBinaryData
        """

        self._n1_sm_info_from_ue = n1_sm_info_from_ue

    @property
    def unknown_n1_sm_info(self):
        """Gets the unknown_n1_sm_info of this VsmfUpdateError.


        :return: The unknown_n1_sm_info of this VsmfUpdateError.
        :rtype: RefToBinaryData
        """
        return self._unknown_n1_sm_info

    @unknown_n1_sm_info.setter
    def unknown_n1_sm_info(self, unknown_n1_sm_info):
        """Sets the unknown_n1_sm_info of this VsmfUpdateError.


        :param unknown_n1_sm_info: The unknown_n1_sm_info of this VsmfUpdateError.
        :type unknown_n1_sm_info: RefToBinaryData
        """

        self._unknown_n1_sm_info = unknown_n1_sm_info

    @property
    def failed_to_assign_ebi_list(self):
        """Gets the failed_to_assign_ebi_list of this VsmfUpdateError.


        :return: The failed_to_assign_ebi_list of this VsmfUpdateError.
        :rtype: List[EpsBearerId]
        """
        return self._failed_to_assign_ebi_list

    @failed_to_assign_ebi_list.setter
    def failed_to_assign_ebi_list(self, failed_to_assign_ebi_list):
        """Sets the failed_to_assign_ebi_list of this VsmfUpdateError.


        :param failed_to_assign_ebi_list: The failed_to_assign_ebi_list of this VsmfUpdateError.
        :type failed_to_assign_ebi_list: List[EpsBearerId]
        """

        self._failed_to_assign_ebi_list = failed_to_assign_ebi_list

    @property
    def ng_ap_cause(self):
        """Gets the ng_ap_cause of this VsmfUpdateError.


        :return: The ng_ap_cause of this VsmfUpdateError.
        :rtype: NgApCause
        """
        return self._ng_ap_cause

    @ng_ap_cause.setter
    def ng_ap_cause(self, ng_ap_cause):
        """Sets the ng_ap_cause of this VsmfUpdateError.


        :param ng_ap_cause: The ng_ap_cause of this VsmfUpdateError.
        :type ng_ap_cause: NgApCause
        """

        self._ng_ap_cause = ng_ap_cause

    @property
    def _5g_mm_cause_value(self):
        """Gets the _5g_mm_cause_value of this VsmfUpdateError.


        :return: The _5g_mm_cause_value of this VsmfUpdateError.
        :rtype: Model5GMmCause
        """
        return self.__5g_mm_cause_value

    @_5g_mm_cause_value.setter
    def _5g_mm_cause_value(self, _5g_mm_cause_value):
        """Sets the _5g_mm_cause_value of this VsmfUpdateError.


        :param _5g_mm_cause_value: The _5g_mm_cause_value of this VsmfUpdateError.
        :type _5g_mm_cause_value: Model5GMmCause
        """

        self.__5g_mm_cause_value = _5g_mm_cause_value

    @property
    def recovery_time(self):
        """Gets the recovery_time of this VsmfUpdateError.


        :return: The recovery_time of this VsmfUpdateError.
        :rtype: datetime
        """
        return self._recovery_time

    @recovery_time.setter
    def recovery_time(self, recovery_time):
        """Sets the recovery_time of this VsmfUpdateError.


        :param recovery_time: The recovery_time of this VsmfUpdateError.
        :type recovery_time: datetime
        """

        self._recovery_time = recovery_time
