# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ebi_arp_mapping import EbiArpMapping  # noqa: F401,E501
from swagger_server.models.eps_bearer_id import EpsBearerId  # noqa: F401,E501
from swagger_server.models.qos_flow_item import QosFlowItem  # noqa: F401,E501
from swagger_server.models.ref_to_binary_data import RefToBinaryData  # noqa: F401,E501
from swagger_server.models.secondary_rat_usage_info import SecondaryRatUsageInfo  # noqa: F401,E501
from swagger_server.models.secondary_rat_usage_report import SecondaryRatUsageReport  # noqa: F401,E501
from swagger_server.models.time_zone import TimeZone  # noqa: F401,E501
from swagger_server.models.user_location import UserLocation  # noqa: F401,E501
from swagger_server import util


class VsmfUpdatedData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, qos_flows_add_mod_list=None, qos_flows_rel_list=None, qos_flows_failedto_add_mod_list=None, qos_flows_failedto_rel_list=None, n1_sm_info_from_ue=None, unknown_n1_sm_info=None, ue_location=None, ue_time_zone=None, add_ue_location=None, assigned_ebi_list=None, failed_to_assign_ebi_list=None, released_ebi_list=None, secondary_rat_usage_report=None, secondary_rat_usage_info=None):  # noqa: E501
        """VsmfUpdatedData - a model defined in Swagger

        :param qos_flows_add_mod_list: The qos_flows_add_mod_list of this VsmfUpdatedData.  # noqa: E501
        :type qos_flows_add_mod_list: List[QosFlowItem]
        :param qos_flows_rel_list: The qos_flows_rel_list of this VsmfUpdatedData.  # noqa: E501
        :type qos_flows_rel_list: List[QosFlowItem]
        :param qos_flows_failedto_add_mod_list: The qos_flows_failedto_add_mod_list of this VsmfUpdatedData.  # noqa: E501
        :type qos_flows_failedto_add_mod_list: List[QosFlowItem]
        :param qos_flows_failedto_rel_list: The qos_flows_failedto_rel_list of this VsmfUpdatedData.  # noqa: E501
        :type qos_flows_failedto_rel_list: List[QosFlowItem]
        :param n1_sm_info_from_ue: The n1_sm_info_from_ue of this VsmfUpdatedData.  # noqa: E501
        :type n1_sm_info_from_ue: RefToBinaryData
        :param unknown_n1_sm_info: The unknown_n1_sm_info of this VsmfUpdatedData.  # noqa: E501
        :type unknown_n1_sm_info: RefToBinaryData
        :param ue_location: The ue_location of this VsmfUpdatedData.  # noqa: E501
        :type ue_location: UserLocation
        :param ue_time_zone: The ue_time_zone of this VsmfUpdatedData.  # noqa: E501
        :type ue_time_zone: TimeZone
        :param add_ue_location: The add_ue_location of this VsmfUpdatedData.  # noqa: E501
        :type add_ue_location: UserLocation
        :param assigned_ebi_list: The assigned_ebi_list of this VsmfUpdatedData.  # noqa: E501
        :type assigned_ebi_list: List[EbiArpMapping]
        :param failed_to_assign_ebi_list: The failed_to_assign_ebi_list of this VsmfUpdatedData.  # noqa: E501
        :type failed_to_assign_ebi_list: List[EpsBearerId]
        :param released_ebi_list: The released_ebi_list of this VsmfUpdatedData.  # noqa: E501
        :type released_ebi_list: List[EpsBearerId]
        :param secondary_rat_usage_report: The secondary_rat_usage_report of this VsmfUpdatedData.  # noqa: E501
        :type secondary_rat_usage_report: List[SecondaryRatUsageReport]
        :param secondary_rat_usage_info: The secondary_rat_usage_info of this VsmfUpdatedData.  # noqa: E501
        :type secondary_rat_usage_info: List[SecondaryRatUsageInfo]
        """
        self.swagger_types = {
            'qos_flows_add_mod_list': List[QosFlowItem],
            'qos_flows_rel_list': List[QosFlowItem],
            'qos_flows_failedto_add_mod_list': List[QosFlowItem],
            'qos_flows_failedto_rel_list': List[QosFlowItem],
            'n1_sm_info_from_ue': RefToBinaryData,
            'unknown_n1_sm_info': RefToBinaryData,
            'ue_location': UserLocation,
            'ue_time_zone': TimeZone,
            'add_ue_location': UserLocation,
            'assigned_ebi_list': List[EbiArpMapping],
            'failed_to_assign_ebi_list': List[EpsBearerId],
            'released_ebi_list': List[EpsBearerId],
            'secondary_rat_usage_report': List[SecondaryRatUsageReport],
            'secondary_rat_usage_info': List[SecondaryRatUsageInfo]
        }

        self.attribute_map = {
            'qos_flows_add_mod_list': 'qosFlowsAddModList',
            'qos_flows_rel_list': 'qosFlowsRelList',
            'qos_flows_failedto_add_mod_list': 'qosFlowsFailedtoAddModList',
            'qos_flows_failedto_rel_list': 'qosFlowsFailedtoRelList',
            'n1_sm_info_from_ue': 'n1SmInfoFromUe',
            'unknown_n1_sm_info': 'unknownN1SmInfo',
            'ue_location': 'ueLocation',
            'ue_time_zone': 'ueTimeZone',
            'add_ue_location': 'addUeLocation',
            'assigned_ebi_list': 'assignedEbiList',
            'failed_to_assign_ebi_list': 'failedToAssignEbiList',
            'released_ebi_list': 'releasedEbiList',
            'secondary_rat_usage_report': 'secondaryRatUsageReport',
            'secondary_rat_usage_info': 'secondaryRatUsageInfo'
        }
        self._qos_flows_add_mod_list = qos_flows_add_mod_list
        self._qos_flows_rel_list = qos_flows_rel_list
        self._qos_flows_failedto_add_mod_list = qos_flows_failedto_add_mod_list
        self._qos_flows_failedto_rel_list = qos_flows_failedto_rel_list
        self._n1_sm_info_from_ue = n1_sm_info_from_ue
        self._unknown_n1_sm_info = unknown_n1_sm_info
        self._ue_location = ue_location
        self._ue_time_zone = ue_time_zone
        self._add_ue_location = add_ue_location
        self._assigned_ebi_list = assigned_ebi_list
        self._failed_to_assign_ebi_list = failed_to_assign_ebi_list
        self._released_ebi_list = released_ebi_list
        self._secondary_rat_usage_report = secondary_rat_usage_report
        self._secondary_rat_usage_info = secondary_rat_usage_info

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VsmfUpdatedData of this VsmfUpdatedData.  # noqa: E501
        :rtype: VsmfUpdatedData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def qos_flows_add_mod_list(self):
        """Gets the qos_flows_add_mod_list of this VsmfUpdatedData.


        :return: The qos_flows_add_mod_list of this VsmfUpdatedData.
        :rtype: List[QosFlowItem]
        """
        return self._qos_flows_add_mod_list

    @qos_flows_add_mod_list.setter
    def qos_flows_add_mod_list(self, qos_flows_add_mod_list):
        """Sets the qos_flows_add_mod_list of this VsmfUpdatedData.


        :param qos_flows_add_mod_list: The qos_flows_add_mod_list of this VsmfUpdatedData.
        :type qos_flows_add_mod_list: List[QosFlowItem]
        """

        self._qos_flows_add_mod_list = qos_flows_add_mod_list

    @property
    def qos_flows_rel_list(self):
        """Gets the qos_flows_rel_list of this VsmfUpdatedData.


        :return: The qos_flows_rel_list of this VsmfUpdatedData.
        :rtype: List[QosFlowItem]
        """
        return self._qos_flows_rel_list

    @qos_flows_rel_list.setter
    def qos_flows_rel_list(self, qos_flows_rel_list):
        """Sets the qos_flows_rel_list of this VsmfUpdatedData.


        :param qos_flows_rel_list: The qos_flows_rel_list of this VsmfUpdatedData.
        :type qos_flows_rel_list: List[QosFlowItem]
        """

        self._qos_flows_rel_list = qos_flows_rel_list

    @property
    def qos_flows_failedto_add_mod_list(self):
        """Gets the qos_flows_failedto_add_mod_list of this VsmfUpdatedData.


        :return: The qos_flows_failedto_add_mod_list of this VsmfUpdatedData.
        :rtype: List[QosFlowItem]
        """
        return self._qos_flows_failedto_add_mod_list

    @qos_flows_failedto_add_mod_list.setter
    def qos_flows_failedto_add_mod_list(self, qos_flows_failedto_add_mod_list):
        """Sets the qos_flows_failedto_add_mod_list of this VsmfUpdatedData.


        :param qos_flows_failedto_add_mod_list: The qos_flows_failedto_add_mod_list of this VsmfUpdatedData.
        :type qos_flows_failedto_add_mod_list: List[QosFlowItem]
        """

        self._qos_flows_failedto_add_mod_list = qos_flows_failedto_add_mod_list

    @property
    def qos_flows_failedto_rel_list(self):
        """Gets the qos_flows_failedto_rel_list of this VsmfUpdatedData.


        :return: The qos_flows_failedto_rel_list of this VsmfUpdatedData.
        :rtype: List[QosFlowItem]
        """
        return self._qos_flows_failedto_rel_list

    @qos_flows_failedto_rel_list.setter
    def qos_flows_failedto_rel_list(self, qos_flows_failedto_rel_list):
        """Sets the qos_flows_failedto_rel_list of this VsmfUpdatedData.


        :param qos_flows_failedto_rel_list: The qos_flows_failedto_rel_list of this VsmfUpdatedData.
        :type qos_flows_failedto_rel_list: List[QosFlowItem]
        """

        self._qos_flows_failedto_rel_list = qos_flows_failedto_rel_list

    @property
    def n1_sm_info_from_ue(self):
        """Gets the n1_sm_info_from_ue of this VsmfUpdatedData.


        :return: The n1_sm_info_from_ue of this VsmfUpdatedData.
        :rtype: RefToBinaryData
        """
        return self._n1_sm_info_from_ue

    @n1_sm_info_from_ue.setter
    def n1_sm_info_from_ue(self, n1_sm_info_from_ue):
        """Sets the n1_sm_info_from_ue of this VsmfUpdatedData.


        :param n1_sm_info_from_ue: The n1_sm_info_from_ue of this VsmfUpdatedData.
        :type n1_sm_info_from_ue: RefToBinaryData
        """

        self._n1_sm_info_from_ue = n1_sm_info_from_ue

    @property
    def unknown_n1_sm_info(self):
        """Gets the unknown_n1_sm_info of this VsmfUpdatedData.


        :return: The unknown_n1_sm_info of this VsmfUpdatedData.
        :rtype: RefToBinaryData
        """
        return self._unknown_n1_sm_info

    @unknown_n1_sm_info.setter
    def unknown_n1_sm_info(self, unknown_n1_sm_info):
        """Sets the unknown_n1_sm_info of this VsmfUpdatedData.


        :param unknown_n1_sm_info: The unknown_n1_sm_info of this VsmfUpdatedData.
        :type unknown_n1_sm_info: RefToBinaryData
        """

        self._unknown_n1_sm_info = unknown_n1_sm_info

    @property
    def ue_location(self):
        """Gets the ue_location of this VsmfUpdatedData.


        :return: The ue_location of this VsmfUpdatedData.
        :rtype: UserLocation
        """
        return self._ue_location

    @ue_location.setter
    def ue_location(self, ue_location):
        """Sets the ue_location of this VsmfUpdatedData.


        :param ue_location: The ue_location of this VsmfUpdatedData.
        :type ue_location: UserLocation
        """

        self._ue_location = ue_location

    @property
    def ue_time_zone(self):
        """Gets the ue_time_zone of this VsmfUpdatedData.


        :return: The ue_time_zone of this VsmfUpdatedData.
        :rtype: TimeZone
        """
        return self._ue_time_zone

    @ue_time_zone.setter
    def ue_time_zone(self, ue_time_zone):
        """Sets the ue_time_zone of this VsmfUpdatedData.


        :param ue_time_zone: The ue_time_zone of this VsmfUpdatedData.
        :type ue_time_zone: TimeZone
        """

        self._ue_time_zone = ue_time_zone

    @property
    def add_ue_location(self):
        """Gets the add_ue_location of this VsmfUpdatedData.


        :return: The add_ue_location of this VsmfUpdatedData.
        :rtype: UserLocation
        """
        return self._add_ue_location

    @add_ue_location.setter
    def add_ue_location(self, add_ue_location):
        """Sets the add_ue_location of this VsmfUpdatedData.


        :param add_ue_location: The add_ue_location of this VsmfUpdatedData.
        :type add_ue_location: UserLocation
        """

        self._add_ue_location = add_ue_location

    @property
    def assigned_ebi_list(self):
        """Gets the assigned_ebi_list of this VsmfUpdatedData.


        :return: The assigned_ebi_list of this VsmfUpdatedData.
        :rtype: List[EbiArpMapping]
        """
        return self._assigned_ebi_list

    @assigned_ebi_list.setter
    def assigned_ebi_list(self, assigned_ebi_list):
        """Sets the assigned_ebi_list of this VsmfUpdatedData.


        :param assigned_ebi_list: The assigned_ebi_list of this VsmfUpdatedData.
        :type assigned_ebi_list: List[EbiArpMapping]
        """

        self._assigned_ebi_list = assigned_ebi_list

    @property
    def failed_to_assign_ebi_list(self):
        """Gets the failed_to_assign_ebi_list of this VsmfUpdatedData.


        :return: The failed_to_assign_ebi_list of this VsmfUpdatedData.
        :rtype: List[EpsBearerId]
        """
        return self._failed_to_assign_ebi_list

    @failed_to_assign_ebi_list.setter
    def failed_to_assign_ebi_list(self, failed_to_assign_ebi_list):
        """Sets the failed_to_assign_ebi_list of this VsmfUpdatedData.


        :param failed_to_assign_ebi_list: The failed_to_assign_ebi_list of this VsmfUpdatedData.
        :type failed_to_assign_ebi_list: List[EpsBearerId]
        """

        self._failed_to_assign_ebi_list = failed_to_assign_ebi_list

    @property
    def released_ebi_list(self):
        """Gets the released_ebi_list of this VsmfUpdatedData.


        :return: The released_ebi_list of this VsmfUpdatedData.
        :rtype: List[EpsBearerId]
        """
        return self._released_ebi_list

    @released_ebi_list.setter
    def released_ebi_list(self, released_ebi_list):
        """Sets the released_ebi_list of this VsmfUpdatedData.


        :param released_ebi_list: The released_ebi_list of this VsmfUpdatedData.
        :type released_ebi_list: List[EpsBearerId]
        """

        self._released_ebi_list = released_ebi_list

    @property
    def secondary_rat_usage_report(self):
        """Gets the secondary_rat_usage_report of this VsmfUpdatedData.


        :return: The secondary_rat_usage_report of this VsmfUpdatedData.
        :rtype: List[SecondaryRatUsageReport]
        """
        return self._secondary_rat_usage_report

    @secondary_rat_usage_report.setter
    def secondary_rat_usage_report(self, secondary_rat_usage_report):
        """Sets the secondary_rat_usage_report of this VsmfUpdatedData.


        :param secondary_rat_usage_report: The secondary_rat_usage_report of this VsmfUpdatedData.
        :type secondary_rat_usage_report: List[SecondaryRatUsageReport]
        """

        self._secondary_rat_usage_report = secondary_rat_usage_report

    @property
    def secondary_rat_usage_info(self):
        """Gets the secondary_rat_usage_info of this VsmfUpdatedData.


        :return: The secondary_rat_usage_info of this VsmfUpdatedData.
        :rtype: List[SecondaryRatUsageInfo]
        """
        return self._secondary_rat_usage_info

    @secondary_rat_usage_info.setter
    def secondary_rat_usage_info(self, secondary_rat_usage_info):
        """Sets the secondary_rat_usage_info of this VsmfUpdatedData.


        :param secondary_rat_usage_info: The secondary_rat_usage_info of this VsmfUpdatedData.
        :type secondary_rat_usage_info: List[SecondaryRatUsageInfo]
        """

        self._secondary_rat_usage_info = secondary_rat_usage_info
