# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.charging_id import ChargingId  # noqa: F401,E501
from swagger_server import util


class AccNetChId(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, acc_net_cha_id_value=None, ref_pcc_rule_ids=None, session_ch_scope=None):  # noqa: E501
        """AccNetChId - a model defined in Swagger

        :param acc_net_cha_id_value: The acc_net_cha_id_value of this AccNetChId.  # noqa: E501
        :type acc_net_cha_id_value: ChargingId
        :param ref_pcc_rule_ids: The ref_pcc_rule_ids of this AccNetChId.  # noqa: E501
        :type ref_pcc_rule_ids: List[str]
        :param session_ch_scope: The session_ch_scope of this AccNetChId.  # noqa: E501
        :type session_ch_scope: bool
        """
        self.swagger_types = {
            'acc_net_cha_id_value': ChargingId,
            'ref_pcc_rule_ids': List[str],
            'session_ch_scope': bool
        }

        self.attribute_map = {
            'acc_net_cha_id_value': 'accNetChaIdValue',
            'ref_pcc_rule_ids': 'refPccRuleIds',
            'session_ch_scope': 'sessionChScope'
        }
        self._acc_net_cha_id_value = acc_net_cha_id_value
        self._ref_pcc_rule_ids = ref_pcc_rule_ids
        self._session_ch_scope = session_ch_scope

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AccNetChId of this AccNetChId.  # noqa: E501
        :rtype: AccNetChId
        """
        return util.deserialize_model(dikt, cls)

    @property
    def acc_net_cha_id_value(self):
        """Gets the acc_net_cha_id_value of this AccNetChId.


        :return: The acc_net_cha_id_value of this AccNetChId.
        :rtype: ChargingId
        """
        return self._acc_net_cha_id_value

    @acc_net_cha_id_value.setter
    def acc_net_cha_id_value(self, acc_net_cha_id_value):
        """Sets the acc_net_cha_id_value of this AccNetChId.


        :param acc_net_cha_id_value: The acc_net_cha_id_value of this AccNetChId.
        :type acc_net_cha_id_value: ChargingId
        """
        if acc_net_cha_id_value is None:
            raise ValueError("Invalid value for `acc_net_cha_id_value`, must not be `None`")  # noqa: E501

        self._acc_net_cha_id_value = acc_net_cha_id_value

    @property
    def ref_pcc_rule_ids(self):
        """Gets the ref_pcc_rule_ids of this AccNetChId.

        Contains the identifier of the PCC rule(s) associated to the provided Access Network Charging Identifier.  # noqa: E501

        :return: The ref_pcc_rule_ids of this AccNetChId.
        :rtype: List[str]
        """
        return self._ref_pcc_rule_ids

    @ref_pcc_rule_ids.setter
    def ref_pcc_rule_ids(self, ref_pcc_rule_ids):
        """Sets the ref_pcc_rule_ids of this AccNetChId.

        Contains the identifier of the PCC rule(s) associated to the provided Access Network Charging Identifier.  # noqa: E501

        :param ref_pcc_rule_ids: The ref_pcc_rule_ids of this AccNetChId.
        :type ref_pcc_rule_ids: List[str]
        """

        self._ref_pcc_rule_ids = ref_pcc_rule_ids

    @property
    def session_ch_scope(self):
        """Gets the session_ch_scope of this AccNetChId.

        When it is included and set to true, indicates the Access Network Charging Identifier applies to the whole PDU Session  # noqa: E501

        :return: The session_ch_scope of this AccNetChId.
        :rtype: bool
        """
        return self._session_ch_scope

    @session_ch_scope.setter
    def session_ch_scope(self, session_ch_scope):
        """Sets the session_ch_scope of this AccNetChId.

        When it is included and set to true, indicates the Access Network Charging Identifier applies to the whole PDU Session  # noqa: E501

        :param session_ch_scope: The session_ch_scope of this AccNetChId.
        :type session_ch_scope: bool
        """

        self._session_ch_scope = session_ch_scope
