# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.eutra_cell_id import EutraCellId  # noqa: F401,E501
from swagger_server.models.plmn_id import PlmnId  # noqa: F401,E501
from swagger_server import util


class Ecgi(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, plmn_id=None, eutra_cell_id=None):  # noqa: E501
        """Ecgi - a model defined in Swagger

        :param plmn_id: The plmn_id of this Ecgi.  # noqa: E501
        :type plmn_id: PlmnId
        :param eutra_cell_id: The eutra_cell_id of this Ecgi.  # noqa: E501
        :type eutra_cell_id: EutraCellId
        """
        self.swagger_types = {
            'plmn_id': PlmnId,
            'eutra_cell_id': EutraCellId
        }

        self.attribute_map = {
            'plmn_id': 'plmnId',
            'eutra_cell_id': 'eutraCellId'
        }
        self._plmn_id = plmn_id
        self._eutra_cell_id = eutra_cell_id

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ecgi of this Ecgi.  # noqa: E501
        :rtype: Ecgi
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plmn_id(self):
        """Gets the plmn_id of this Ecgi.


        :return: The plmn_id of this Ecgi.
        :rtype: PlmnId
        """
        return self._plmn_id

    @plmn_id.setter
    def plmn_id(self, plmn_id):
        """Sets the plmn_id of this Ecgi.


        :param plmn_id: The plmn_id of this Ecgi.
        :type plmn_id: PlmnId
        """
        if plmn_id is None:
            raise ValueError("Invalid value for `plmn_id`, must not be `None`")  # noqa: E501

        self._plmn_id = plmn_id

    @property
    def eutra_cell_id(self):
        """Gets the eutra_cell_id of this Ecgi.


        :return: The eutra_cell_id of this Ecgi.
        :rtype: EutraCellId
        """
        return self._eutra_cell_id

    @eutra_cell_id.setter
    def eutra_cell_id(self, eutra_cell_id):
        """Sets the eutra_cell_id of this Ecgi.


        :param eutra_cell_id: The eutra_cell_id of this Ecgi.
        :type eutra_cell_id: EutraCellId
        """
        if eutra_cell_id is None:
            raise ValueError("Invalid value for `eutra_cell_id`, must not be `None`")  # noqa: E501

        self._eutra_cell_id = eutra_cell_id
