# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.nr_cell_id import NrCellId  # noqa: F401,E501
from swagger_server.models.plmn_id import PlmnId  # noqa: F401,E501
from swagger_server import util


class Ncgi(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, plmn_id=None, nr_cell_id=None):  # noqa: E501
        """Ncgi - a model defined in Swagger

        :param plmn_id: The plmn_id of this Ncgi.  # noqa: E501
        :type plmn_id: PlmnId
        :param nr_cell_id: The nr_cell_id of this Ncgi.  # noqa: E501
        :type nr_cell_id: NrCellId
        """
        self.swagger_types = {
            'plmn_id': PlmnId,
            'nr_cell_id': NrCellId
        }

        self.attribute_map = {
            'plmn_id': 'plmnId',
            'nr_cell_id': 'nrCellId'
        }
        self._plmn_id = plmn_id
        self._nr_cell_id = nr_cell_id

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ncgi of this Ncgi.  # noqa: E501
        :rtype: Ncgi
        """
        return util.deserialize_model(dikt, cls)

    @property
    def plmn_id(self):
        """Gets the plmn_id of this Ncgi.


        :return: The plmn_id of this Ncgi.
        :rtype: PlmnId
        """
        return self._plmn_id

    @plmn_id.setter
    def plmn_id(self, plmn_id):
        """Sets the plmn_id of this Ncgi.


        :param plmn_id: The plmn_id of this Ncgi.
        :type plmn_id: PlmnId
        """
        if plmn_id is None:
            raise ValueError("Invalid value for `plmn_id`, must not be `None`")  # noqa: E501

        self._plmn_id = plmn_id

    @property
    def nr_cell_id(self):
        """Gets the nr_cell_id of this Ncgi.


        :return: The nr_cell_id of this Ncgi.
        :rtype: NrCellId
        """
        return self._nr_cell_id

    @nr_cell_id.setter
    def nr_cell_id(self, nr_cell_id):
        """Sets the nr_cell_id of this Ncgi.


        :param nr_cell_id: The nr_cell_id of this Ncgi.
        :type nr_cell_id: NrCellId
        """
        if nr_cell_id is None:
            raise ValueError("Invalid value for `nr_cell_id`, must not be `None`")  # noqa: E501

        self._nr_cell_id = nr_cell_id
