# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.ecgi import Ecgi  # noqa: F401,E501
from swagger_server.models.global_ran_node_id import GlobalRanNodeId  # noqa: F401,E501
from swagger_server.models.ncgi import Ncgi  # noqa: F401,E501
from swagger_server.models.presence_state import PresenceState  # noqa: F401,E501
from swagger_server.models.tai import Tai  # noqa: F401,E501
from swagger_server import util


class PresenceInfoRm(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, pra_id=None, presence_state=None, tracking_area_list=None, ecgi_list=None, ncgi_list=None, global_ran_node_id_list=None):  # noqa: E501
        """PresenceInfoRm - a model defined in Swagger

        :param pra_id: The pra_id of this PresenceInfoRm.  # noqa: E501
        :type pra_id: str
        :param presence_state: The presence_state of this PresenceInfoRm.  # noqa: E501
        :type presence_state: PresenceState
        :param tracking_area_list: The tracking_area_list of this PresenceInfoRm.  # noqa: E501
        :type tracking_area_list: List[Tai]
        :param ecgi_list: The ecgi_list of this PresenceInfoRm.  # noqa: E501
        :type ecgi_list: List[Ecgi]
        :param ncgi_list: The ncgi_list of this PresenceInfoRm.  # noqa: E501
        :type ncgi_list: List[Ncgi]
        :param global_ran_node_id_list: The global_ran_node_id_list of this PresenceInfoRm.  # noqa: E501
        :type global_ran_node_id_list: List[GlobalRanNodeId]
        """
        self.swagger_types = {
            'pra_id': str,
            'presence_state': PresenceState,
            'tracking_area_list': List[Tai],
            'ecgi_list': List[Ecgi],
            'ncgi_list': List[Ncgi],
            'global_ran_node_id_list': List[GlobalRanNodeId]
        }

        self.attribute_map = {
            'pra_id': 'praId',
            'presence_state': 'presenceState',
            'tracking_area_list': 'trackingAreaList',
            'ecgi_list': 'ecgiList',
            'ncgi_list': 'ncgiList',
            'global_ran_node_id_list': 'globalRanNodeIdList'
        }
        self._pra_id = pra_id
        self._presence_state = presence_state
        self._tracking_area_list = tracking_area_list
        self._ecgi_list = ecgi_list
        self._ncgi_list = ncgi_list
        self._global_ran_node_id_list = global_ran_node_id_list

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PresenceInfoRm of this PresenceInfoRm.  # noqa: E501
        :rtype: PresenceInfoRm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def pra_id(self):
        """Gets the pra_id of this PresenceInfoRm.


        :return: The pra_id of this PresenceInfoRm.
        :rtype: str
        """
        return self._pra_id

    @pra_id.setter
    def pra_id(self, pra_id):
        """Sets the pra_id of this PresenceInfoRm.


        :param pra_id: The pra_id of this PresenceInfoRm.
        :type pra_id: str
        """

        self._pra_id = pra_id

    @property
    def presence_state(self):
        """Gets the presence_state of this PresenceInfoRm.


        :return: The presence_state of this PresenceInfoRm.
        :rtype: PresenceState
        """
        return self._presence_state

    @presence_state.setter
    def presence_state(self, presence_state):
        """Sets the presence_state of this PresenceInfoRm.


        :param presence_state: The presence_state of this PresenceInfoRm.
        :type presence_state: PresenceState
        """

        self._presence_state = presence_state

    @property
    def tracking_area_list(self):
        """Gets the tracking_area_list of this PresenceInfoRm.


        :return: The tracking_area_list of this PresenceInfoRm.
        :rtype: List[Tai]
        """
        return self._tracking_area_list

    @tracking_area_list.setter
    def tracking_area_list(self, tracking_area_list):
        """Sets the tracking_area_list of this PresenceInfoRm.


        :param tracking_area_list: The tracking_area_list of this PresenceInfoRm.
        :type tracking_area_list: List[Tai]
        """

        self._tracking_area_list = tracking_area_list

    @property
    def ecgi_list(self):
        """Gets the ecgi_list of this PresenceInfoRm.


        :return: The ecgi_list of this PresenceInfoRm.
        :rtype: List[Ecgi]
        """
        return self._ecgi_list

    @ecgi_list.setter
    def ecgi_list(self, ecgi_list):
        """Sets the ecgi_list of this PresenceInfoRm.


        :param ecgi_list: The ecgi_list of this PresenceInfoRm.
        :type ecgi_list: List[Ecgi]
        """

        self._ecgi_list = ecgi_list

    @property
    def ncgi_list(self):
        """Gets the ncgi_list of this PresenceInfoRm.


        :return: The ncgi_list of this PresenceInfoRm.
        :rtype: List[Ncgi]
        """
        return self._ncgi_list

    @ncgi_list.setter
    def ncgi_list(self, ncgi_list):
        """Sets the ncgi_list of this PresenceInfoRm.


        :param ncgi_list: The ncgi_list of this PresenceInfoRm.
        :type ncgi_list: List[Ncgi]
        """

        self._ncgi_list = ncgi_list

    @property
    def global_ran_node_id_list(self):
        """Gets the global_ran_node_id_list of this PresenceInfoRm.


        :return: The global_ran_node_id_list of this PresenceInfoRm.
        :rtype: List[GlobalRanNodeId]
        """
        return self._global_ran_node_id_list

    @global_ran_node_id_list.setter
    def global_ran_node_id_list(self, global_ran_node_id_list):
        """Sets the global_ran_node_id_list of this PresenceInfoRm.


        :param global_ran_node_id_list: The global_ran_node_id_list of this PresenceInfoRm.
        :type global_ran_node_id_list: List[GlobalRanNodeId]
        """

        self._global_ran_node_id_list = global_ran_node_id_list
