# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class RequestedUsageData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, ref_um_ids=None, all_um_ids=None):  # noqa: E501
        """RequestedUsageData - a model defined in Swagger

        :param ref_um_ids: The ref_um_ids of this RequestedUsageData.  # noqa: E501
        :type ref_um_ids: List[str]
        :param all_um_ids: The all_um_ids of this RequestedUsageData.  # noqa: E501
        :type all_um_ids: bool
        """
        self.swagger_types = {
            'ref_um_ids': List[str],
            'all_um_ids': bool
        }

        self.attribute_map = {
            'ref_um_ids': 'refUmIds',
            'all_um_ids': 'allUmIds'
        }
        self._ref_um_ids = ref_um_ids
        self._all_um_ids = all_um_ids

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestedUsageData of this RequestedUsageData.  # noqa: E501
        :rtype: RequestedUsageData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def ref_um_ids(self):
        """Gets the ref_um_ids of this RequestedUsageData.

        An array of usage monitoring data id references to the usage monitoring data instances for which the PCF is requesting a usage report. This attribute shall only be provided when allUmIds is not set to true.  # noqa: E501

        :return: The ref_um_ids of this RequestedUsageData.
        :rtype: List[str]
        """
        return self._ref_um_ids

    @ref_um_ids.setter
    def ref_um_ids(self, ref_um_ids):
        """Sets the ref_um_ids of this RequestedUsageData.

        An array of usage monitoring data id references to the usage monitoring data instances for which the PCF is requesting a usage report. This attribute shall only be provided when allUmIds is not set to true.  # noqa: E501

        :param ref_um_ids: The ref_um_ids of this RequestedUsageData.
        :type ref_um_ids: List[str]
        """

        self._ref_um_ids = ref_um_ids

    @property
    def all_um_ids(self):
        """Gets the all_um_ids of this RequestedUsageData.

        Th ooleanean indicates whether requested usage data applies to all usage monitoring data instances. When it's not included, it means requested usage data shall only apply to the usage monitoring data instances referenced by the refUmIds attribute.  # noqa: E501

        :return: The all_um_ids of this RequestedUsageData.
        :rtype: bool
        """
        return self._all_um_ids

    @all_um_ids.setter
    def all_um_ids(self, all_um_ids):
        """Sets the all_um_ids of this RequestedUsageData.

        Th ooleanean indicates whether requested usage data applies to all usage monitoring data instances. When it's not included, it means requested usage data shall only apply to the usage monitoring data instances referenced by the refUmIds attribute.  # noqa: E501

        :param all_um_ids: The all_um_ids of this RequestedUsageData.
        :type all_um_ids: bool
        """

        self._all_um_ids = all_um_ids
