# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.bit_rate import BitRate  # noqa: F401,E501
from swagger_server.models.model5_qi import Model5Qi  # noqa: F401,E501
from swagger_server import util


class RequestedQos(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _5qi=None, gbr_ul=None, gbr_dl=None):  # noqa: E501
        """RequestedQos - a model defined in Swagger

        :param _5qi: The _5qi of this RequestedQos.  # noqa: E501
        :type _5qi: Model5Qi
        :param gbr_ul: The gbr_ul of this RequestedQos.  # noqa: E501
        :type gbr_ul: BitRate
        :param gbr_dl: The gbr_dl of this RequestedQos.  # noqa: E501
        :type gbr_dl: BitRate
        """
        self.swagger_types = {
            '_5qi': Model5Qi,
            'gbr_ul': BitRate,
            'gbr_dl': BitRate
        }

        self.attribute_map = {
            '_5qi': '5qi',
            'gbr_ul': 'gbrUl',
            'gbr_dl': 'gbrDl'
        }
        self.__5qi = _5qi
        self._gbr_ul = gbr_ul
        self._gbr_dl = gbr_dl

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RequestedQos of this RequestedQos.  # noqa: E501
        :rtype: RequestedQos
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _5qi(self):
        """Gets the _5qi of this RequestedQos.


        :return: The _5qi of this RequestedQos.
        :rtype: Model5Qi
        """
        return self.__5qi

    @_5qi.setter
    def _5qi(self, _5qi):
        """Sets the _5qi of this RequestedQos.


        :param _5qi: The _5qi of this RequestedQos.
        :type _5qi: Model5Qi
        """
        if _5qi is None:
            raise ValueError("Invalid value for `_5qi`, must not be `None`")  # noqa: E501

        self.__5qi = _5qi

    @property
    def gbr_ul(self):
        """Gets the gbr_ul of this RequestedQos.


        :return: The gbr_ul of this RequestedQos.
        :rtype: BitRate
        """
        return self._gbr_ul

    @gbr_ul.setter
    def gbr_ul(self, gbr_ul):
        """Sets the gbr_ul of this RequestedQos.


        :param gbr_ul: The gbr_ul of this RequestedQos.
        :type gbr_ul: BitRate
        """

        self._gbr_ul = gbr_ul

    @property
    def gbr_dl(self):
        """Gets the gbr_dl of this RequestedQos.


        :return: The gbr_dl of this RequestedQos.
        :rtype: BitRate
        """
        return self._gbr_dl

    @gbr_dl.setter
    def gbr_dl(self, gbr_dl):
        """Sets the gbr_dl of this RequestedQos.


        :param gbr_dl: The gbr_dl of this RequestedQos.
        :type gbr_dl: BitRate
        """

        self._gbr_dl = gbr_dl
