# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.sm_policy_decision import SmPolicyDecision  # noqa: F401,E501
from swagger_server.models.uri import Uri  # noqa: F401,E501
from swagger_server import util


class SmPolicyNotification(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, resource_uri=None, sm_policy_decision=None):  # noqa: E501
        """SmPolicyNotification - a model defined in Swagger

        :param resource_uri: The resource_uri of this SmPolicyNotification.  # noqa: E501
        :type resource_uri: Uri
        :param sm_policy_decision: The sm_policy_decision of this SmPolicyNotification.  # noqa: E501
        :type sm_policy_decision: SmPolicyDecision
        """
        self.swagger_types = {
            'resource_uri': Uri,
            'sm_policy_decision': SmPolicyDecision
        }

        self.attribute_map = {
            'resource_uri': 'resourceUri',
            'sm_policy_decision': 'smPolicyDecision'
        }
        self._resource_uri = resource_uri
        self._sm_policy_decision = sm_policy_decision

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SmPolicyNotification of this SmPolicyNotification.  # noqa: E501
        :rtype: SmPolicyNotification
        """
        return util.deserialize_model(dikt, cls)

    @property
    def resource_uri(self):
        """Gets the resource_uri of this SmPolicyNotification.


        :return: The resource_uri of this SmPolicyNotification.
        :rtype: Uri
        """
        return self._resource_uri

    @resource_uri.setter
    def resource_uri(self, resource_uri):
        """Sets the resource_uri of this SmPolicyNotification.


        :param resource_uri: The resource_uri of this SmPolicyNotification.
        :type resource_uri: Uri
        """

        self._resource_uri = resource_uri

    @property
    def sm_policy_decision(self):
        """Gets the sm_policy_decision of this SmPolicyNotification.


        :return: The sm_policy_decision of this SmPolicyNotification.
        :rtype: SmPolicyDecision
        """
        return self._sm_policy_decision

    @sm_policy_decision.setter
    def sm_policy_decision(self, sm_policy_decision):
        """Sets the sm_policy_decision of this SmPolicyNotification.


        :param sm_policy_decision: The sm_policy_decision of this SmPolicyNotification.
        :type sm_policy_decision: SmPolicyDecision
        """

        self._sm_policy_decision = sm_policy_decision
