# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.dnai_change_type import DnaiChangeType  # noqa: F401,E501
from swagger_server.models.uri import Uri  # noqa: F401,E501
from swagger_server import util


class UpPathChgEvent(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, notification_uri=None, notif_corre_id=None, dnai_chg_type=None):  # noqa: E501
        """UpPathChgEvent - a model defined in Swagger

        :param notification_uri: The notification_uri of this UpPathChgEvent.  # noqa: E501
        :type notification_uri: Uri
        :param notif_corre_id: The notif_corre_id of this UpPathChgEvent.  # noqa: E501
        :type notif_corre_id: str
        :param dnai_chg_type: The dnai_chg_type of this UpPathChgEvent.  # noqa: E501
        :type dnai_chg_type: DnaiChangeType
        """
        self.swagger_types = {
            'notification_uri': Uri,
            'notif_corre_id': str,
            'dnai_chg_type': DnaiChangeType
        }

        self.attribute_map = {
            'notification_uri': 'notificationUri',
            'notif_corre_id': 'notifCorreId',
            'dnai_chg_type': 'dnaiChgType'
        }
        self._notification_uri = notification_uri
        self._notif_corre_id = notif_corre_id
        self._dnai_chg_type = dnai_chg_type

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UpPathChgEvent of this UpPathChgEvent.  # noqa: E501
        :rtype: UpPathChgEvent
        """
        return util.deserialize_model(dikt, cls)

    @property
    def notification_uri(self):
        """Gets the notification_uri of this UpPathChgEvent.


        :return: The notification_uri of this UpPathChgEvent.
        :rtype: Uri
        """
        return self._notification_uri

    @notification_uri.setter
    def notification_uri(self, notification_uri):
        """Sets the notification_uri of this UpPathChgEvent.


        :param notification_uri: The notification_uri of this UpPathChgEvent.
        :type notification_uri: Uri
        """
        if notification_uri is None:
            raise ValueError("Invalid value for `notification_uri`, must not be `None`")  # noqa: E501

        self._notification_uri = notification_uri

    @property
    def notif_corre_id(self):
        """Gets the notif_corre_id of this UpPathChgEvent.

        It is used to set the value of Notification Correlation ID in the notification sent by the SMF.  # noqa: E501

        :return: The notif_corre_id of this UpPathChgEvent.
        :rtype: str
        """
        return self._notif_corre_id

    @notif_corre_id.setter
    def notif_corre_id(self, notif_corre_id):
        """Sets the notif_corre_id of this UpPathChgEvent.

        It is used to set the value of Notification Correlation ID in the notification sent by the SMF.  # noqa: E501

        :param notif_corre_id: The notif_corre_id of this UpPathChgEvent.
        :type notif_corre_id: str
        """
        if notif_corre_id is None:
            raise ValueError("Invalid value for `notif_corre_id`, must not be `None`")  # noqa: E501

        self._notif_corre_id = notif_corre_id

    @property
    def dnai_chg_type(self):
        """Gets the dnai_chg_type of this UpPathChgEvent.


        :return: The dnai_chg_type of this UpPathChgEvent.
        :rtype: DnaiChangeType
        """
        return self._dnai_chg_type

    @dnai_chg_type.setter
    def dnai_chg_type(self, dnai_chg_type):
        """Sets the dnai_chg_type of this UpPathChgEvent.


        :param dnai_chg_type: The dnai_chg_type of this UpPathChgEvent.
        :type dnai_chg_type: DnaiChangeType
        """
        if dnai_chg_type is None:
            raise ValueError("Invalid value for `dnai_chg_type`, must not be `None`")  # noqa: E501

        self._dnai_chg_type = dnai_chg_type
