# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.eutra_location import EutraLocation  # noqa: F401,E501
from swagger_server.models.n3ga_location import N3gaLocation  # noqa: F401,E501
from swagger_server.models.nr_location import NrLocation  # noqa: F401,E501
from swagger_server import util


class UserLocation(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, eutra_location=None, nr_location=None, n3ga_location=None):  # noqa: E501
        """UserLocation - a model defined in Swagger

        :param eutra_location: The eutra_location of this UserLocation.  # noqa: E501
        :type eutra_location: EutraLocation
        :param nr_location: The nr_location of this UserLocation.  # noqa: E501
        :type nr_location: NrLocation
        :param n3ga_location: The n3ga_location of this UserLocation.  # noqa: E501
        :type n3ga_location: N3gaLocation
        """
        self.swagger_types = {
            'eutra_location': EutraLocation,
            'nr_location': NrLocation,
            'n3ga_location': N3gaLocation
        }

        self.attribute_map = {
            'eutra_location': 'eutraLocation',
            'nr_location': 'nrLocation',
            'n3ga_location': 'n3gaLocation'
        }
        self._eutra_location = eutra_location
        self._nr_location = nr_location
        self._n3ga_location = n3ga_location

    @classmethod
    def from_dict(cls, dikt):
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserLocation of this UserLocation.  # noqa: E501
        :rtype: UserLocation
        """
        return util.deserialize_model(dikt, cls)

    @property
    def eutra_location(self):
        """Gets the eutra_location of this UserLocation.


        :return: The eutra_location of this UserLocation.
        :rtype: EutraLocation
        """
        return self._eutra_location

    @eutra_location.setter
    def eutra_location(self, eutra_location):
        """Sets the eutra_location of this UserLocation.


        :param eutra_location: The eutra_location of this UserLocation.
        :type eutra_location: EutraLocation
        """

        self._eutra_location = eutra_location

    @property
    def nr_location(self):
        """Gets the nr_location of this UserLocation.


        :return: The nr_location of this UserLocation.
        :rtype: NrLocation
        """
        return self._nr_location

    @nr_location.setter
    def nr_location(self, nr_location):
        """Sets the nr_location of this UserLocation.


        :param nr_location: The nr_location of this UserLocation.
        :type nr_location: NrLocation
        """

        self._nr_location = nr_location

    @property
    def n3ga_location(self):
        """Gets the n3ga_location of this UserLocation.


        :return: The n3ga_location of this UserLocation.
        :rtype: N3gaLocation
        """
        return self._n3ga_location

    @n3ga_location.setter
    def n3ga_location(self, n3ga_location):
        """Sets the n3ga_location of this UserLocation.


        :param n3ga_location: The n3ga_location of this UserLocation.
        :type n3ga_location: N3gaLocation
        """

        self._n3ga_location = n3ga_location
